# coding: utf-8

"""
    smritea SDK API

    Public SDK API for smritea AI memory system — programmatic memory operations via API key

    The version of the OpenAPI document: 1.0.0
    Contact: support@smritea.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ErrorsErrorCode(str, Enum):
    """
    ErrorsErrorCode
    """

    """
    allowed enum values
    """
    ErrValidation = 'VALIDATION_ERROR'
    ErrInvalidInput = 'INVALID_INPUT'
    ErrUnauthorized = 'UNAUTHORIZED'
    ErrForbidden = 'FORBIDDEN'
    ErrInvalidToken = 'INVALID_TOKEN'
    ErrExpiredToken = 'EXPIRED_TOKEN'
    ErrInvalidAPIKey = 'INVALID_API_KEY'
    ErrNotFound = 'NOT_FOUND'
    ErrAlreadyExists = 'ALREADY_EXISTS'
    ErrConflict = 'CONFLICT'
    ErrQuotaExceeded = 'QUOTA_EXCEEDED'
    ErrInsufficientQuota = 'INSUFFICIENT_QUOTA'
    ErrInternal = 'INTERNAL_ERROR'
    ErrDatabaseError = 'DATABASE_ERROR'
    ErrCodeEmailNotVerified = 'EMAIL_NOT_VERIFIED'
    ErrCodePasswordResetExpired = 'PASSWORD_RESET_EXPIRED'
    ErrCodeOAuthProviderNotSupported = 'OAUTH_PROVIDER_NOT_SUPPORTED'
    ErrCodeOAuthStateMismatch = 'OAUTH_STATE_MISMATCH'
    ErrCodeAccountAlreadyLinked = 'ACCOUNT_ALREADY_LINKED'
    ErrCodeCannotUnlinkOnlyAuthMethod = 'CANNOT_UNLINK_ONLY_AUTH_METHOD'
    ErrCodeNotOrgMember = 'NOT_ORG_MEMBER'
    ErrCodeInsufficientPermission = 'INSUFFICIENT_PERMISSION'
    ErrCodeOrgSlugTaken = 'ORG_SLUG_TAKEN'
    ErrCodeNotTeamMember = 'NOT_TEAM_MEMBER'
    ErrCodeInvitationNotFound = 'INVITATION_NOT_FOUND'
    ErrCodeInvitationExpired = 'INVITATION_EXPIRED'
    ErrCodeInvitationAlreadyAccepted = 'INVITATION_ALREADY_ACCEPTED'
    ErrCodeUserAlreadyExists = 'USER_ALREADY_EXISTS'
    ErrCodeInvalidEmail = 'INVALID_EMAIL'
    ErrCodeEmailAlreadyVerified = 'EMAIL_ALREADY_VERIFIED'
    ErrCodeNoPasswordSet = 'NO_PASSWORD_SET'
    ErrCodePasswordAlreadySet = 'PASSWORD_ALREADY_SET'
    ErrCodeRateLimitExceeded = 'RATE_LIMIT_EXCEEDED'
    ErrCodeAppNameExistsInOrg = 'APP_NAME_EXISTS_IN_ORG'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorsErrorCode from a JSON string"""
        return cls(json.loads(json_str))


