/*
 * smritea SDK API
 *
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Smritea.Internal.Autogen.Client.FileParameter;
using OpenAPIDateConverter = Smritea.Internal.Autogen.Client.OpenAPIDateConverter;

namespace Smritea.Internal.Autogen.Model
{
    /// <summary>
    /// APIError
    /// </summary>
    [DataContract(Name = "APIError")]
    public partial class APIError : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="APIError" /> class.
        /// </summary>
        /// <param name="code">Code is a machine-readable error code (e.g., \&quot;validation_error\&quot;, \&quot;not_found\&quot;)..</param>
        /// <param name="message">Message is a human-readable description of what went wrong..</param>
        /// <param name="retryable">Retryable reports whether the client should retry (additive, spec doc-175); set by the error middleware, always true for 429..</param>
        public APIError(string code = default, string message = default, bool retryable = default)
        {
            this.Code = code;
            this.Message = message;
            this.Retryable = retryable;
        }

        /// <summary>
        /// Code is a machine-readable error code (e.g., \&quot;validation_error\&quot;, \&quot;not_found\&quot;).
        /// </summary>
        /// <value>Code is a machine-readable error code (e.g., \&quot;validation_error\&quot;, \&quot;not_found\&quot;).</value>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string Code { get; set; }

        /// <summary>
        /// Message is a human-readable description of what went wrong.
        /// </summary>
        /// <value>Message is a human-readable description of what went wrong.</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Retryable reports whether the client should retry (additive, spec doc-175); set by the error middleware, always true for 429.
        /// </summary>
        /// <value>Retryable reports whether the client should retry (additive, spec doc-175); set by the error middleware, always true for 429.</value>
        [DataMember(Name = "retryable", EmitDefaultValue = true)]
        public bool Retryable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class APIError {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Retryable: ").Append(Retryable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
