/*
 * smritea SDK API
 *
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Smritea.Internal.Autogen.Client.FileParameter;
using OpenAPIDateConverter = Smritea.Internal.Autogen.Client.OpenAPIDateConverter;

namespace Smritea.Internal.Autogen.Model
{
    /// <summary>
    /// CommondtoMemoryScope
    /// </summary>
    [DataContract(Name = "commondto.MemoryScope")]
    public partial class CommondtoMemoryScope : IValidatableObject
    {
        /// <summary>
        /// Defines ActorType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActorTypeEnum
        {
            /// <summary>
            /// Enum User for value: user
            /// </summary>
            [EnumMember(Value = "user")]
            User = 1,

            /// <summary>
            /// Enum Agent for value: agent
            /// </summary>
            [EnumMember(Value = "agent")]
            Agent = 2,

            /// <summary>
            /// Enum System for value: system
            /// </summary>
            [EnumMember(Value = "system")]
            System = 3
        }


        /// <summary>
        /// Gets or Sets ActorType
        /// </summary>
        [DataMember(Name = "actor_type", EmitDefaultValue = false)]
        public ActorTypeEnum? ActorType { get; set; }
        /// <summary>
        /// Defines SourceType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SourceTypeEnum
        {
            /// <summary>
            /// Enum Conversation for value: conversation
            /// </summary>
            [EnumMember(Value = "conversation")]
            Conversation = 1,

            /// <summary>
            /// Enum Document for value: document
            /// </summary>
            [EnumMember(Value = "document")]
            Document = 2,

            /// <summary>
            /// Enum Api for value: api
            /// </summary>
            [EnumMember(Value = "api")]
            Api = 3
        }


        /// <summary>
        /// Gets or Sets SourceType
        /// </summary>
        [DataMember(Name = "source_type", EmitDefaultValue = false)]
        public SourceTypeEnum? SourceType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CommondtoMemoryScope" /> class.
        /// </summary>
        /// <param name="actorId">actorId.</param>
        /// <param name="actorName">actorName.</param>
        /// <param name="actorType">actorType.</param>
        /// <param name="conversationId">conversationId.</param>
        /// <param name="participantIds">ParticipantIDs lists actor IDs whose shared conversations to search. The search service expands this to all conversations where ALL listed actors participated (AND semantics — conversations missing even one actor are excluded). Mutually exclusive with ConversationID; if both are set, ConversationID takes precedence. Minimum 2 IDs required..</param>
        /// <param name="sourceType">sourceType.</param>
        public CommondtoMemoryScope(string actorId = default, string actorName = default, ActorTypeEnum? actorType = default, string conversationId = default, List<string> participantIds = default, SourceTypeEnum? sourceType = default)
        {
            this.ActorId = actorId;
            this.ActorName = actorName;
            this.ActorType = actorType;
            this.ConversationId = conversationId;
            this.ParticipantIds = participantIds;
            this.SourceType = sourceType;
        }

        /// <summary>
        /// Gets or Sets ActorId
        /// </summary>
        [DataMember(Name = "actor_id", EmitDefaultValue = false)]
        public string ActorId { get; set; }

        /// <summary>
        /// Gets or Sets ActorName
        /// </summary>
        [DataMember(Name = "actor_name", EmitDefaultValue = false)]
        public string ActorName { get; set; }

        /// <summary>
        /// Gets or Sets ConversationId
        /// </summary>
        [DataMember(Name = "conversation_id", EmitDefaultValue = false)]
        public string ConversationId { get; set; }

        /// <summary>
        /// ParticipantIDs lists actor IDs whose shared conversations to search. The search service expands this to all conversations where ALL listed actors participated (AND semantics — conversations missing even one actor are excluded). Mutually exclusive with ConversationID; if both are set, ConversationID takes precedence. Minimum 2 IDs required.
        /// </summary>
        /// <value>ParticipantIDs lists actor IDs whose shared conversations to search. The search service expands this to all conversations where ALL listed actors participated (AND semantics — conversations missing even one actor are excluded). Mutually exclusive with ConversationID; if both are set, ConversationID takes precedence. Minimum 2 IDs required.</value>
        [DataMember(Name = "participant_ids", EmitDefaultValue = false)]
        public List<string> ParticipantIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CommondtoMemoryScope {\n");
            sb.Append("  ActorId: ").Append(ActorId).Append("\n");
            sb.Append("  ActorName: ").Append(ActorName).Append("\n");
            sb.Append("  ActorType: ").Append(ActorType).Append("\n");
            sb.Append("  ConversationId: ").Append(ConversationId).Append("\n");
            sb.Append("  ParticipantIds: ").Append(ParticipantIds).Append("\n");
            sb.Append("  SourceType: ").Append(SourceType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
