/*
 * smritea SDK API
 *
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Smritea.Internal.Autogen.Client.FileParameter;
using OpenAPIDateConverter = Smritea.Internal.Autogen.Client.OpenAPIDateConverter;

namespace Smritea.Internal.Autogen.Model
{
    /// <summary>
    /// CommondtoFactExtractionConfig
    /// </summary>
    [DataContract(Name = "commondto.FactExtractionConfig")]
    public partial class CommondtoFactExtractionConfig : IValidatableObject
    {
        /// <summary>
        /// Strategy is the fact extraction strategy to use. Default: \&quot;llm_fact_extraction\&quot;
        /// </summary>
        /// <value>Strategy is the fact extraction strategy to use. Default: \&quot;llm_fact_extraction\&quot;</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StrategyEnum
        {
            /// <summary>
            /// Enum LlmFactExtraction for value: llm_fact_extraction
            /// </summary>
            [EnumMember(Value = "llm_fact_extraction")]
            LlmFactExtraction = 1
        }


        /// <summary>
        /// Strategy is the fact extraction strategy to use. Default: \&quot;llm_fact_extraction\&quot;
        /// </summary>
        /// <value>Strategy is the fact extraction strategy to use. Default: \&quot;llm_fact_extraction\&quot;</value>
        [DataMember(Name = "strategy", EmitDefaultValue = false)]
        public StrategyEnum? Strategy { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CommondtoFactExtractionConfig" /> class.
        /// </summary>
        /// <param name="maxPasses">MaxPasses controls how many extraction passes to perform. -1 &#x3D; explicitly skip fact extraction (sentinel value). 0 &#x3D; not specified (Go zero value), use default. 1-5 &#x3D; run N extraction passes. Default is 1 (single pass) so that fact extraction is enabled by default..</param>
        /// <param name="maxTokens">MaxTokens is the maximum completion tokens for LLM responses. 0 &#x3D; not set (use default). TODO(https://linear.app/bityantriki/issue/BIT-83): revert gte&#x3D;0 to gte&#x3D;100 once pedantigo applies defaults to nested structs during Validate().</param>
        /// <param name="minImportance">MinImportance is the minimum importance threshold for extracted facts (0.0 to 1.0). Facts below this threshold are filtered out..</param>
        /// <param name="model">Model is the LLM model to use (empty &#x3D; use provider default)..</param>
        /// <param name="strategy">Strategy is the fact extraction strategy to use. Default: \&quot;llm_fact_extraction\&quot;.</param>
        /// <param name="temperature">Temperature controls LLM randomness (0.0 &#x3D; deterministic, higher &#x3D; creative)..</param>
        public CommondtoFactExtractionConfig(int maxPasses = default, int maxTokens = default, decimal minImportance = default, string model = default, StrategyEnum? strategy = default, decimal temperature = default)
        {
            this.MaxPasses = maxPasses;
            this.MaxTokens = maxTokens;
            this.MinImportance = minImportance;
            this.Model = model;
            this.Strategy = strategy;
            this.Temperature = temperature;
        }

        /// <summary>
        /// MaxPasses controls how many extraction passes to perform. -1 &#x3D; explicitly skip fact extraction (sentinel value). 0 &#x3D; not specified (Go zero value), use default. 1-5 &#x3D; run N extraction passes. Default is 1 (single pass) so that fact extraction is enabled by default.
        /// </summary>
        /// <value>MaxPasses controls how many extraction passes to perform. -1 &#x3D; explicitly skip fact extraction (sentinel value). 0 &#x3D; not specified (Go zero value), use default. 1-5 &#x3D; run N extraction passes. Default is 1 (single pass) so that fact extraction is enabled by default.</value>
        [DataMember(Name = "max_passes", EmitDefaultValue = false)]
        public int MaxPasses { get; set; }

        /// <summary>
        /// MaxTokens is the maximum completion tokens for LLM responses. 0 &#x3D; not set (use default). TODO(https://linear.app/bityantriki/issue/BIT-83): revert gte&#x3D;0 to gte&#x3D;100 once pedantigo applies defaults to nested structs during Validate()
        /// </summary>
        /// <value>MaxTokens is the maximum completion tokens for LLM responses. 0 &#x3D; not set (use default). TODO(https://linear.app/bityantriki/issue/BIT-83): revert gte&#x3D;0 to gte&#x3D;100 once pedantigo applies defaults to nested structs during Validate()</value>
        [DataMember(Name = "max_tokens", EmitDefaultValue = false)]
        public int MaxTokens { get; set; }

        /// <summary>
        /// MinImportance is the minimum importance threshold for extracted facts (0.0 to 1.0). Facts below this threshold are filtered out.
        /// </summary>
        /// <value>MinImportance is the minimum importance threshold for extracted facts (0.0 to 1.0). Facts below this threshold are filtered out.</value>
        [DataMember(Name = "min_importance", EmitDefaultValue = false)]
        public decimal MinImportance { get; set; }

        /// <summary>
        /// Model is the LLM model to use (empty &#x3D; use provider default).
        /// </summary>
        /// <value>Model is the LLM model to use (empty &#x3D; use provider default).</value>
        [DataMember(Name = "model", EmitDefaultValue = false)]
        public string Model { get; set; }

        /// <summary>
        /// Temperature controls LLM randomness (0.0 &#x3D; deterministic, higher &#x3D; creative).
        /// </summary>
        /// <value>Temperature controls LLM randomness (0.0 &#x3D; deterministic, higher &#x3D; creative).</value>
        [DataMember(Name = "temperature", EmitDefaultValue = false)]
        public decimal Temperature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CommondtoFactExtractionConfig {\n");
            sb.Append("  MaxPasses: ").Append(MaxPasses).Append("\n");
            sb.Append("  MaxTokens: ").Append(MaxTokens).Append("\n");
            sb.Append("  MinImportance: ").Append(MinImportance).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Strategy: ").Append(Strategy).Append("\n");
            sb.Append("  Temperature: ").Append(Temperature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
