/*
 * smritea SDK API
 *
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Smritea.Internal.Autogen.Client.FileParameter;
using OpenAPIDateConverter = Smritea.Internal.Autogen.Client.OpenAPIDateConverter;

namespace Smritea.Internal.Autogen.Model
{
    /// <summary>
    /// CommondtoPersonaDomainConfig
    /// </summary>
    [DataContract(Name = "commondto.PersonaDomainConfig")]
    public partial class CommondtoPersonaDomainConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommondtoPersonaDomainConfig" /> class.
        /// </summary>
        /// <param name="description">Description describes what kind of traits this domain captures..</param>
        /// <param name="isDefault">IsDefault indicates if this domain is included by default..</param>
        /// <param name="name">Name is the domain identifier (e.g., \&quot;preferences\&quot;, \&quot;interests\&quot;, \&quot;demographics\&quot;)..</param>
        /// <param name="traits">Traits lists expected trait names for this domain (optional, for LLM guidance)..</param>
        public CommondtoPersonaDomainConfig(string description = default, bool isDefault = default, string name = default, List<string> traits = default)
        {
            this.Description = description;
            this.IsDefault = isDefault;
            this.Name = name;
            this.Traits = traits;
        }

        /// <summary>
        /// Description describes what kind of traits this domain captures.
        /// </summary>
        /// <value>Description describes what kind of traits this domain captures.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// IsDefault indicates if this domain is included by default.
        /// </summary>
        /// <value>IsDefault indicates if this domain is included by default.</value>
        [DataMember(Name = "is_default", EmitDefaultValue = true)]
        public bool IsDefault { get; set; }

        /// <summary>
        /// Name is the domain identifier (e.g., \&quot;preferences\&quot;, \&quot;interests\&quot;, \&quot;demographics\&quot;).
        /// </summary>
        /// <value>Name is the domain identifier (e.g., \&quot;preferences\&quot;, \&quot;interests\&quot;, \&quot;demographics\&quot;).</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Traits lists expected trait names for this domain (optional, for LLM guidance).
        /// </summary>
        /// <value>Traits lists expected trait names for this domain (optional, for LLM guidance).</value>
        [DataMember(Name = "traits", EmitDefaultValue = false)]
        public List<string> Traits { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CommondtoPersonaDomainConfig {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  IsDefault: ").Append(IsDefault).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Traits: ").Append(Traits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
