/*
 * smritea SDK API
 *
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Smritea.Internal.Autogen.Client.FileParameter;
using OpenAPIDateConverter = Smritea.Internal.Autogen.Client.OpenAPIDateConverter;

namespace Smritea.Internal.Autogen.Model
{
    /// <summary>
    /// Defines errors.ErrorCode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ErrorsErrorCode
    {
        /// <summary>
        /// Enum ErrValidation for value: VALIDATION_ERROR
        /// </summary>
        [EnumMember(Value = "VALIDATION_ERROR")]
        ErrValidation = 1,

        /// <summary>
        /// Enum ErrInvalidInput for value: INVALID_INPUT
        /// </summary>
        [EnumMember(Value = "INVALID_INPUT")]
        ErrInvalidInput = 2,

        /// <summary>
        /// Enum ErrUnauthorized for value: UNAUTHORIZED
        /// </summary>
        [EnumMember(Value = "UNAUTHORIZED")]
        ErrUnauthorized = 3,

        /// <summary>
        /// Enum ErrForbidden for value: FORBIDDEN
        /// </summary>
        [EnumMember(Value = "FORBIDDEN")]
        ErrForbidden = 4,

        /// <summary>
        /// Enum ErrInvalidToken for value: INVALID_TOKEN
        /// </summary>
        [EnumMember(Value = "INVALID_TOKEN")]
        ErrInvalidToken = 5,

        /// <summary>
        /// Enum ErrExpiredToken for value: EXPIRED_TOKEN
        /// </summary>
        [EnumMember(Value = "EXPIRED_TOKEN")]
        ErrExpiredToken = 6,

        /// <summary>
        /// Enum ErrInvalidAPIKey for value: INVALID_API_KEY
        /// </summary>
        [EnumMember(Value = "INVALID_API_KEY")]
        ErrInvalidAPIKey = 7,

        /// <summary>
        /// Enum ErrNotFound for value: NOT_FOUND
        /// </summary>
        [EnumMember(Value = "NOT_FOUND")]
        ErrNotFound = 8,

        /// <summary>
        /// Enum ErrAlreadyExists for value: ALREADY_EXISTS
        /// </summary>
        [EnumMember(Value = "ALREADY_EXISTS")]
        ErrAlreadyExists = 9,

        /// <summary>
        /// Enum ErrConflict for value: CONFLICT
        /// </summary>
        [EnumMember(Value = "CONFLICT")]
        ErrConflict = 10,

        /// <summary>
        /// Enum ErrQuotaExceeded for value: QUOTA_EXCEEDED
        /// </summary>
        [EnumMember(Value = "QUOTA_EXCEEDED")]
        ErrQuotaExceeded = 11,

        /// <summary>
        /// Enum ErrInsufficientQuota for value: INSUFFICIENT_QUOTA
        /// </summary>
        [EnumMember(Value = "INSUFFICIENT_QUOTA")]
        ErrInsufficientQuota = 12,

        /// <summary>
        /// Enum ErrInternal for value: INTERNAL_ERROR
        /// </summary>
        [EnumMember(Value = "INTERNAL_ERROR")]
        ErrInternal = 13,

        /// <summary>
        /// Enum ErrDatabaseError for value: DATABASE_ERROR
        /// </summary>
        [EnumMember(Value = "DATABASE_ERROR")]
        ErrDatabaseError = 14,

        /// <summary>
        /// Enum ErrCodeEmailNotVerified for value: EMAIL_NOT_VERIFIED
        /// </summary>
        [EnumMember(Value = "EMAIL_NOT_VERIFIED")]
        ErrCodeEmailNotVerified = 15,

        /// <summary>
        /// Enum ErrCodePasswordResetExpired for value: PASSWORD_RESET_EXPIRED
        /// </summary>
        [EnumMember(Value = "PASSWORD_RESET_EXPIRED")]
        ErrCodePasswordResetExpired = 16,

        /// <summary>
        /// Enum ErrCodeOAuthProviderNotSupported for value: OAUTH_PROVIDER_NOT_SUPPORTED
        /// </summary>
        [EnumMember(Value = "OAUTH_PROVIDER_NOT_SUPPORTED")]
        ErrCodeOAuthProviderNotSupported = 17,

        /// <summary>
        /// Enum ErrCodeOAuthStateMismatch for value: OAUTH_STATE_MISMATCH
        /// </summary>
        [EnumMember(Value = "OAUTH_STATE_MISMATCH")]
        ErrCodeOAuthStateMismatch = 18,

        /// <summary>
        /// Enum ErrCodeAccountAlreadyLinked for value: ACCOUNT_ALREADY_LINKED
        /// </summary>
        [EnumMember(Value = "ACCOUNT_ALREADY_LINKED")]
        ErrCodeAccountAlreadyLinked = 19,

        /// <summary>
        /// Enum ErrCodeCannotUnlinkOnlyAuthMethod for value: CANNOT_UNLINK_ONLY_AUTH_METHOD
        /// </summary>
        [EnumMember(Value = "CANNOT_UNLINK_ONLY_AUTH_METHOD")]
        ErrCodeCannotUnlinkOnlyAuthMethod = 20,

        /// <summary>
        /// Enum ErrCodeNotOrgMember for value: NOT_ORG_MEMBER
        /// </summary>
        [EnumMember(Value = "NOT_ORG_MEMBER")]
        ErrCodeNotOrgMember = 21,

        /// <summary>
        /// Enum ErrCodeInsufficientPermission for value: INSUFFICIENT_PERMISSION
        /// </summary>
        [EnumMember(Value = "INSUFFICIENT_PERMISSION")]
        ErrCodeInsufficientPermission = 22,

        /// <summary>
        /// Enum ErrCodeOrgSlugTaken for value: ORG_SLUG_TAKEN
        /// </summary>
        [EnumMember(Value = "ORG_SLUG_TAKEN")]
        ErrCodeOrgSlugTaken = 23,

        /// <summary>
        /// Enum ErrCodeNotTeamMember for value: NOT_TEAM_MEMBER
        /// </summary>
        [EnumMember(Value = "NOT_TEAM_MEMBER")]
        ErrCodeNotTeamMember = 24,

        /// <summary>
        /// Enum ErrCodeInvitationNotFound for value: INVITATION_NOT_FOUND
        /// </summary>
        [EnumMember(Value = "INVITATION_NOT_FOUND")]
        ErrCodeInvitationNotFound = 25,

        /// <summary>
        /// Enum ErrCodeInvitationExpired for value: INVITATION_EXPIRED
        /// </summary>
        [EnumMember(Value = "INVITATION_EXPIRED")]
        ErrCodeInvitationExpired = 26,

        /// <summary>
        /// Enum ErrCodeInvitationAlreadyAccepted for value: INVITATION_ALREADY_ACCEPTED
        /// </summary>
        [EnumMember(Value = "INVITATION_ALREADY_ACCEPTED")]
        ErrCodeInvitationAlreadyAccepted = 27,

        /// <summary>
        /// Enum ErrCodeUserAlreadyExists for value: USER_ALREADY_EXISTS
        /// </summary>
        [EnumMember(Value = "USER_ALREADY_EXISTS")]
        ErrCodeUserAlreadyExists = 28,

        /// <summary>
        /// Enum ErrCodeInvalidEmail for value: INVALID_EMAIL
        /// </summary>
        [EnumMember(Value = "INVALID_EMAIL")]
        ErrCodeInvalidEmail = 29,

        /// <summary>
        /// Enum ErrCodeEmailAlreadyVerified for value: EMAIL_ALREADY_VERIFIED
        /// </summary>
        [EnumMember(Value = "EMAIL_ALREADY_VERIFIED")]
        ErrCodeEmailAlreadyVerified = 30,

        /// <summary>
        /// Enum ErrCodeNoPasswordSet for value: NO_PASSWORD_SET
        /// </summary>
        [EnumMember(Value = "NO_PASSWORD_SET")]
        ErrCodeNoPasswordSet = 31,

        /// <summary>
        /// Enum ErrCodePasswordAlreadySet for value: PASSWORD_ALREADY_SET
        /// </summary>
        [EnumMember(Value = "PASSWORD_ALREADY_SET")]
        ErrCodePasswordAlreadySet = 32,

        /// <summary>
        /// Enum ErrCodeRateLimitExceeded for value: RATE_LIMIT_EXCEEDED
        /// </summary>
        [EnumMember(Value = "RATE_LIMIT_EXCEEDED")]
        ErrCodeRateLimitExceeded = 33,

        /// <summary>
        /// Enum ErrCodeAppNameExistsInOrg for value: APP_NAME_EXISTS_IN_ORG
        /// </summary>
        [EnumMember(Value = "APP_NAME_EXISTS_IN_ORG")]
        ErrCodeAppNameExistsInOrg = 34,

        /// <summary>
        /// Enum ErrCodeCreditsExhausted for value: CREDITS_EXHAUSTED
        /// </summary>
        [EnumMember(Value = "CREDITS_EXHAUSTED")]
        ErrCodeCreditsExhausted = 35,

        /// <summary>
        /// Enum ErrCodeInsufficientCredits for value: INSUFFICIENT_CREDITS
        /// </summary>
        [EnumMember(Value = "INSUFFICIENT_CREDITS")]
        ErrCodeInsufficientCredits = 36,

        /// <summary>
        /// Enum ErrCodeCreditsExpired for value: CREDITS_EXPIRED
        /// </summary>
        [EnumMember(Value = "CREDITS_EXPIRED")]
        ErrCodeCreditsExpired = 37
    }

}
