/*
 * smritea SDK API
 *
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Smritea.Internal.Autogen.Client.FileParameter;
using OpenAPIDateConverter = Smritea.Internal.Autogen.Client.OpenAPIDateConverter;

namespace Smritea.Internal.Autogen.Model
{
    /// <summary>
    /// MemoryCreateMemoryRequest
    /// </summary>
    [DataContract(Name = "memory.CreateMemoryRequest")]
    public partial class MemoryCreateMemoryRequest : IValidatableObject
    {
        /// <summary>
        /// ActorType is the type of the actor (user|agent|system). Required when ActorID is present; omit for conversation-level or app-level memories.
        /// </summary>
        /// <value>ActorType is the type of the actor (user|agent|system). Required when ActorID is present; omit for conversation-level or app-level memories.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActorTypeEnum
        {
            /// <summary>
            /// Enum User for value: user
            /// </summary>
            [EnumMember(Value = "user")]
            User = 1,

            /// <summary>
            /// Enum Agent for value: agent
            /// </summary>
            [EnumMember(Value = "agent")]
            Agent = 2,

            /// <summary>
            /// Enum System for value: system
            /// </summary>
            [EnumMember(Value = "system")]
            System = 3
        }


        /// <summary>
        /// ActorType is the type of the actor (user|agent|system). Required when ActorID is present; omit for conversation-level or app-level memories.
        /// </summary>
        /// <value>ActorType is the type of the actor (user|agent|system). Required when ActorID is present; omit for conversation-level or app-level memories.</value>
        [DataMember(Name = "actor_type", EmitDefaultValue = false)]
        public ActorTypeEnum? ActorType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MemoryCreateMemoryRequest" /> class.
        /// </summary>
        /// <param name="activeFrom">ActiveFrom is when this memory becomes contextually valid (defaults to now if omitted).</param>
        /// <param name="activeTo">ActiveTo is when this memory stops being valid (optional, nil &#x3D; still valid).</param>
        /// <param name="actorId">ActorID is the actor identifier (conditionally required with ActorType). Required for actor-level memories; omit for conversation-level or app-level memories..</param>
        /// <param name="actorName">ActorName is the name of the actor (optional, max 255 chars).</param>
        /// <param name="actorType">ActorType is the type of the actor (user|agent|system). Required when ActorID is present; omit for conversation-level or app-level memories..</param>
        /// <param name="appId">AppID is the application identifier (required).</param>
        /// <param name="content">Content is the memory content (required, min 1 char).</param>
        /// <param name="conversationId">ConversationID is the conversation identifier (optional, UUID).</param>
        /// <param name="conversationMessageId">ConversationMessageID is the conversation message identifier (optional, UUID).</param>
        /// <param name="entityExtractionOverrides">EntityExtractionOverrides overrides App-level entity extraction config (nil &#x3D; use App defaults). Only non-zero fields in overrides replace app-level values..</param>
        /// <param name="factExtractionOverrides">FactExtractionOverrides overrides App-level fact extraction config (nil &#x3D; use App defaults). Only non-zero fields in overrides replace app-level values..</param>
        /// <param name="metadata">Metadata contains flexible memory metadata (optional).</param>
        /// <param name="personaExtractionOverrides">PersonaExtractionOverrides overrides App-level persona extraction config (nil &#x3D; use App defaults). Only non-zero fields in overrides replace app-level values. This is a stub for v1 - the actual LLM-based persona extraction is deferred to a future task..</param>
        /// <param name="relativeStanding">RelativeStanding groups importance and temporal decay parameters. If nil on input, defaults are applied (importance&#x3D;1.0, decay_factor&#x3D;0.2, decay_function&#x3D;exponential)..</param>
        public MemoryCreateMemoryRequest(string activeFrom = default, string activeTo = default, string actorId = default, string actorName = default, ActorTypeEnum? actorType = default, string appId = default, string content = default, string conversationId = default, string conversationMessageId = default, CommondtoEntityExtractionConfig entityExtractionOverrides = default, CommondtoFactExtractionConfig factExtractionOverrides = default, Object metadata = default, CommondtoPersonaExtractionConfig personaExtractionOverrides = default, CommondtoRelativeStandingConfig relativeStanding = default)
        {
            this.ActiveFrom = activeFrom;
            this.ActiveTo = activeTo;
            this.ActorId = actorId;
            this.ActorName = actorName;
            this.ActorType = actorType;
            this.AppId = appId;
            this.Content = content;
            this.ConversationId = conversationId;
            this.ConversationMessageId = conversationMessageId;
            this.EntityExtractionOverrides = entityExtractionOverrides;
            this.FactExtractionOverrides = factExtractionOverrides;
            this.Metadata = metadata;
            this.PersonaExtractionOverrides = personaExtractionOverrides;
            this.RelativeStanding = relativeStanding;
        }

        /// <summary>
        /// ActiveFrom is when this memory becomes contextually valid (defaults to now if omitted)
        /// </summary>
        /// <value>ActiveFrom is when this memory becomes contextually valid (defaults to now if omitted)</value>
        [DataMember(Name = "active_from", EmitDefaultValue = false)]
        public string ActiveFrom { get; set; }

        /// <summary>
        /// ActiveTo is when this memory stops being valid (optional, nil &#x3D; still valid)
        /// </summary>
        /// <value>ActiveTo is when this memory stops being valid (optional, nil &#x3D; still valid)</value>
        [DataMember(Name = "active_to", EmitDefaultValue = false)]
        public string ActiveTo { get; set; }

        /// <summary>
        /// ActorID is the actor identifier (conditionally required with ActorType). Required for actor-level memories; omit for conversation-level or app-level memories.
        /// </summary>
        /// <value>ActorID is the actor identifier (conditionally required with ActorType). Required for actor-level memories; omit for conversation-level or app-level memories.</value>
        [DataMember(Name = "actor_id", EmitDefaultValue = false)]
        public string ActorId { get; set; }

        /// <summary>
        /// ActorName is the name of the actor (optional, max 255 chars)
        /// </summary>
        /// <value>ActorName is the name of the actor (optional, max 255 chars)</value>
        [DataMember(Name = "actor_name", EmitDefaultValue = false)]
        public string ActorName { get; set; }

        /// <summary>
        /// AppID is the application identifier (required)
        /// </summary>
        /// <value>AppID is the application identifier (required)</value>
        [DataMember(Name = "app_id", EmitDefaultValue = false)]
        public string AppId { get; set; }

        /// <summary>
        /// Content is the memory content (required, min 1 char)
        /// </summary>
        /// <value>Content is the memory content (required, min 1 char)</value>
        [DataMember(Name = "content", EmitDefaultValue = false)]
        public string Content { get; set; }

        /// <summary>
        /// ConversationID is the conversation identifier (optional, UUID)
        /// </summary>
        /// <value>ConversationID is the conversation identifier (optional, UUID)</value>
        [DataMember(Name = "conversation_id", EmitDefaultValue = false)]
        public string ConversationId { get; set; }

        /// <summary>
        /// ConversationMessageID is the conversation message identifier (optional, UUID)
        /// </summary>
        /// <value>ConversationMessageID is the conversation message identifier (optional, UUID)</value>
        [DataMember(Name = "conversation_message_id", EmitDefaultValue = false)]
        public string ConversationMessageId { get; set; }

        /// <summary>
        /// EntityExtractionOverrides overrides App-level entity extraction config (nil &#x3D; use App defaults). Only non-zero fields in overrides replace app-level values.
        /// </summary>
        /// <value>EntityExtractionOverrides overrides App-level entity extraction config (nil &#x3D; use App defaults). Only non-zero fields in overrides replace app-level values.</value>
        [DataMember(Name = "entity_extraction_overrides", EmitDefaultValue = false)]
        public CommondtoEntityExtractionConfig EntityExtractionOverrides { get; set; }

        /// <summary>
        /// FactExtractionOverrides overrides App-level fact extraction config (nil &#x3D; use App defaults). Only non-zero fields in overrides replace app-level values.
        /// </summary>
        /// <value>FactExtractionOverrides overrides App-level fact extraction config (nil &#x3D; use App defaults). Only non-zero fields in overrides replace app-level values.</value>
        [DataMember(Name = "fact_extraction_overrides", EmitDefaultValue = false)]
        public CommondtoFactExtractionConfig FactExtractionOverrides { get; set; }

        /// <summary>
        /// Metadata contains flexible memory metadata (optional)
        /// </summary>
        /// <value>Metadata contains flexible memory metadata (optional)</value>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Object Metadata { get; set; }

        /// <summary>
        /// PersonaExtractionOverrides overrides App-level persona extraction config (nil &#x3D; use App defaults). Only non-zero fields in overrides replace app-level values. This is a stub for v1 - the actual LLM-based persona extraction is deferred to a future task.
        /// </summary>
        /// <value>PersonaExtractionOverrides overrides App-level persona extraction config (nil &#x3D; use App defaults). Only non-zero fields in overrides replace app-level values. This is a stub for v1 - the actual LLM-based persona extraction is deferred to a future task.</value>
        [DataMember(Name = "persona_extraction_overrides", EmitDefaultValue = false)]
        public CommondtoPersonaExtractionConfig PersonaExtractionOverrides { get; set; }

        /// <summary>
        /// RelativeStanding groups importance and temporal decay parameters. If nil on input, defaults are applied (importance&#x3D;1.0, decay_factor&#x3D;0.2, decay_function&#x3D;exponential).
        /// </summary>
        /// <value>RelativeStanding groups importance and temporal decay parameters. If nil on input, defaults are applied (importance&#x3D;1.0, decay_factor&#x3D;0.2, decay_function&#x3D;exponential).</value>
        [DataMember(Name = "relative_standing", EmitDefaultValue = false)]
        public CommondtoRelativeStandingConfig RelativeStanding { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MemoryCreateMemoryRequest {\n");
            sb.Append("  ActiveFrom: ").Append(ActiveFrom).Append("\n");
            sb.Append("  ActiveTo: ").Append(ActiveTo).Append("\n");
            sb.Append("  ActorId: ").Append(ActorId).Append("\n");
            sb.Append("  ActorName: ").Append(ActorName).Append("\n");
            sb.Append("  ActorType: ").Append(ActorType).Append("\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  ConversationId: ").Append(ConversationId).Append("\n");
            sb.Append("  ConversationMessageId: ").Append(ConversationMessageId).Append("\n");
            sb.Append("  EntityExtractionOverrides: ").Append(EntityExtractionOverrides).Append("\n");
            sb.Append("  FactExtractionOverrides: ").Append(FactExtractionOverrides).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  PersonaExtractionOverrides: ").Append(PersonaExtractionOverrides).Append("\n");
            sb.Append("  RelativeStanding: ").Append(RelativeStanding).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
