/*
 * smritea SDK API
 *
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Smritea.Internal.Autogen.Client.FileParameter;
using OpenAPIDateConverter = Smritea.Internal.Autogen.Client.OpenAPIDateConverter;

namespace Smritea.Internal.Autogen.Model
{
    /// <summary>
    /// MemoryMemoryResponse
    /// </summary>
    [DataContract(Name = "memory.MemoryResponse")]
    public partial class MemoryMemoryResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MemoryMemoryResponse" /> class.
        /// </summary>
        /// <param name="activeFrom">activeFrom.</param>
        /// <param name="activeTo">activeTo.</param>
        /// <param name="appId">appId.</param>
        /// <param name="content">content.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="id">id.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="relativeStanding">relativeStanding.</param>
        /// <param name="scope">Scope contains the memory&#39;s actor, conversation, and source context..</param>
        /// <param name="updatedAt">updatedAt.</param>
        public MemoryMemoryResponse(string activeFrom = default, string activeTo = default, string appId = default, string content = default, string createdAt = default, string id = default, Object metadata = default, CommondtoRelativeStandingConfig relativeStanding = default, CommondtoMemoryScope scope = default, string updatedAt = default)
        {
            this.ActiveFrom = activeFrom;
            this.ActiveTo = activeTo;
            this.AppId = appId;
            this.Content = content;
            this.CreatedAt = createdAt;
            this.Id = id;
            this.Metadata = metadata;
            this.RelativeStanding = relativeStanding;
            this.Scope = scope;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets ActiveFrom
        /// </summary>
        [DataMember(Name = "active_from", EmitDefaultValue = false)]
        public string ActiveFrom { get; set; }

        /// <summary>
        /// Gets or Sets ActiveTo
        /// </summary>
        [DataMember(Name = "active_to", EmitDefaultValue = false)]
        public string ActiveTo { get; set; }

        /// <summary>
        /// Gets or Sets AppId
        /// </summary>
        [DataMember(Name = "app_id", EmitDefaultValue = false)]
        public string AppId { get; set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name = "content", EmitDefaultValue = false)]
        public string Content { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Gets or Sets RelativeStanding
        /// </summary>
        [DataMember(Name = "relative_standing", EmitDefaultValue = false)]
        public CommondtoRelativeStandingConfig RelativeStanding { get; set; }

        /// <summary>
        /// Scope contains the memory&#39;s actor, conversation, and source context.
        /// </summary>
        /// <value>Scope contains the memory&#39;s actor, conversation, and source context.</value>
        [DataMember(Name = "scope", EmitDefaultValue = false)]
        public CommondtoMemoryScope Scope { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updated_at", EmitDefaultValue = false)]
        public string UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MemoryMemoryResponse {\n");
            sb.Append("  ActiveFrom: ").Append(ActiveFrom).Append("\n");
            sb.Append("  ActiveTo: ").Append(ActiveTo).Append("\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  RelativeStanding: ").Append(RelativeStanding).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
