/*
 * smritea SDK API
 *
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Smritea.Internal.Autogen.Client.FileParameter;
using OpenAPIDateConverter = Smritea.Internal.Autogen.Client.OpenAPIDateConverter;

namespace Smritea.Internal.Autogen.Model
{
    /// <summary>
    /// SearchMemoryRequest
    /// </summary>
    [DataContract(Name = "SearchMemoryRequest")]
    public partial class SearchMemoryRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Method
        /// </summary>
        [DataMember(Name = "method", EmitDefaultValue = false)]
        public SearchMethod? Method { get; set; }

        /// <summary>
        /// RerankerType overrides the reranker for this request (optional). If nil, uses app config reranker. Only applies to deep_search method.
        /// </summary>
        /// <value>RerankerType overrides the reranker for this request (optional). If nil, uses app config reranker. Only applies to deep_search method.</value>
        [DataMember(Name = "reranker_type", EmitDefaultValue = false)]
        public RerankerType? RerankerType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchMemoryRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchMemoryRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchMemoryRequest" /> class.
        /// </summary>
        /// <param name="appId">appId (required).</param>
        /// <param name="fromTime">FromTime filters memories that overlap with time range [FromTime, ToTime] (ISO 8601 format). Must be used together with ToTime..</param>
        /// <param name="graphDepth">0 &#x3D; system graph_max_hops; 1..services.search.graph_max_hops_max.</param>
        /// <param name="limit">0 &#x3D; app top_n; must be &lt;&#x3D; services.search.top_n_max (checked in the service layer)..</param>
        /// <param name="metadataFilter">MetadataFilter filters memories by user-provided key-value metadata. Only memories whose metadata contains ALL specified key-value pairs are returned..</param>
        /// <param name="method">method.</param>
        /// <param name="query">query (required).</param>
        /// <param name="rerankerType">RerankerType overrides the reranker for this request (optional). If nil, uses app config reranker. Only applies to deep_search method..</param>
        /// <param name="scope">Scope groups actor, conversation, and source filtering fields. Zero-value fields mean \&quot;no filter\&quot; (searches across all)..</param>
        /// <param name="speakerActorId">SpeakerActorID identifies which actor is making this search request. It is NEVER used for filtering — it does not narrow, exclude, or bias which memories are returned. It exists purely for identification: audit logging, telemetry, and any future personalization/access-control hook that needs to know \&quot;who is asking\&quot; independent of \&quot;which memories to include.\&quot; That second concern (result filtering) is entirely owned by Scope below. Deliberately top-level, not nested inside Scope, so it can never be confused with — or accidentally coupled to — the filter fields. Optional: omit if the caller has no meaningful requester identity (e.g. an anonymous or system-initiated search)..</param>
        /// <param name="toTime">ToTime is the end of the time range filter (ISO 8601 format). Must be used together with FromTime..</param>
        /// <param name="validAt">ValidAt filters memories valid at a specific point in time (ISO 8601 format). A memory is valid if: active_from &lt;&#x3D; ValidAt AND (active_to is null OR active_to &gt;&#x3D; ValidAt) Mutually exclusive with FromTime/ToTime..</param>
        public SearchMemoryRequest(string appId = default, string fromTime = default, int graphDepth = default, int limit = default, Object metadataFilter = default, SearchMethod? method = default, string query = default, RerankerType? rerankerType = default, MemoryScope scope = default, string speakerActorId = default, string toTime = default, string validAt = default)
        {
            // to ensure "appId" is required (not null)
            if (appId == null)
            {
                throw new ArgumentNullException("appId is a required property for SearchMemoryRequest and cannot be null");
            }
            this.AppId = appId;
            // to ensure "query" is required (not null)
            if (query == null)
            {
                throw new ArgumentNullException("query is a required property for SearchMemoryRequest and cannot be null");
            }
            this.Query = query;
            this.FromTime = fromTime;
            this.GraphDepth = graphDepth;
            this.Limit = limit;
            this.MetadataFilter = metadataFilter;
            this.Method = method;
            this.RerankerType = rerankerType;
            this.Scope = scope;
            this.SpeakerActorId = speakerActorId;
            this.ToTime = toTime;
            this.ValidAt = validAt;
        }

        /// <summary>
        /// Gets or Sets AppId
        /// </summary>
        [DataMember(Name = "app_id", IsRequired = true, EmitDefaultValue = true)]
        public string AppId { get; set; }

        /// <summary>
        /// FromTime filters memories that overlap with time range [FromTime, ToTime] (ISO 8601 format). Must be used together with ToTime.
        /// </summary>
        /// <value>FromTime filters memories that overlap with time range [FromTime, ToTime] (ISO 8601 format). Must be used together with ToTime.</value>
        [DataMember(Name = "from_time", EmitDefaultValue = false)]
        public string FromTime { get; set; }

        /// <summary>
        /// 0 &#x3D; system graph_max_hops; 1..services.search.graph_max_hops_max
        /// </summary>
        /// <value>0 &#x3D; system graph_max_hops; 1..services.search.graph_max_hops_max</value>
        [DataMember(Name = "graph_depth", EmitDefaultValue = false)]
        public int GraphDepth { get; set; }

        /// <summary>
        /// 0 &#x3D; app top_n; must be &lt;&#x3D; services.search.top_n_max (checked in the service layer).
        /// </summary>
        /// <value>0 &#x3D; app top_n; must be &lt;&#x3D; services.search.top_n_max (checked in the service layer).</value>
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public int Limit { get; set; }

        /// <summary>
        /// MetadataFilter filters memories by user-provided key-value metadata. Only memories whose metadata contains ALL specified key-value pairs are returned.
        /// </summary>
        /// <value>MetadataFilter filters memories by user-provided key-value metadata. Only memories whose metadata contains ALL specified key-value pairs are returned.</value>
        [DataMember(Name = "metadata_filter", EmitDefaultValue = false)]
        public Object MetadataFilter { get; set; }

        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        [DataMember(Name = "query", IsRequired = true, EmitDefaultValue = true)]
        public string Query { get; set; }

        /// <summary>
        /// Scope groups actor, conversation, and source filtering fields. Zero-value fields mean \&quot;no filter\&quot; (searches across all).
        /// </summary>
        /// <value>Scope groups actor, conversation, and source filtering fields. Zero-value fields mean \&quot;no filter\&quot; (searches across all).</value>
        [DataMember(Name = "scope", EmitDefaultValue = false)]
        public MemoryScope Scope { get; set; }

        /// <summary>
        /// SpeakerActorID identifies which actor is making this search request. It is NEVER used for filtering — it does not narrow, exclude, or bias which memories are returned. It exists purely for identification: audit logging, telemetry, and any future personalization/access-control hook that needs to know \&quot;who is asking\&quot; independent of \&quot;which memories to include.\&quot; That second concern (result filtering) is entirely owned by Scope below. Deliberately top-level, not nested inside Scope, so it can never be confused with — or accidentally coupled to — the filter fields. Optional: omit if the caller has no meaningful requester identity (e.g. an anonymous or system-initiated search).
        /// </summary>
        /// <value>SpeakerActorID identifies which actor is making this search request. It is NEVER used for filtering — it does not narrow, exclude, or bias which memories are returned. It exists purely for identification: audit logging, telemetry, and any future personalization/access-control hook that needs to know \&quot;who is asking\&quot; independent of \&quot;which memories to include.\&quot; That second concern (result filtering) is entirely owned by Scope below. Deliberately top-level, not nested inside Scope, so it can never be confused with — or accidentally coupled to — the filter fields. Optional: omit if the caller has no meaningful requester identity (e.g. an anonymous or system-initiated search).</value>
        [DataMember(Name = "speaker_actor_id", EmitDefaultValue = false)]
        public string SpeakerActorId { get; set; }

        /// <summary>
        /// ToTime is the end of the time range filter (ISO 8601 format). Must be used together with FromTime.
        /// </summary>
        /// <value>ToTime is the end of the time range filter (ISO 8601 format). Must be used together with FromTime.</value>
        [DataMember(Name = "to_time", EmitDefaultValue = false)]
        public string ToTime { get; set; }

        /// <summary>
        /// ValidAt filters memories valid at a specific point in time (ISO 8601 format). A memory is valid if: active_from &lt;&#x3D; ValidAt AND (active_to is null OR active_to &gt;&#x3D; ValidAt) Mutually exclusive with FromTime/ToTime.
        /// </summary>
        /// <value>ValidAt filters memories valid at a specific point in time (ISO 8601 format). A memory is valid if: active_from &lt;&#x3D; ValidAt AND (active_to is null OR active_to &gt;&#x3D; ValidAt) Mutually exclusive with FromTime/ToTime.</value>
        [DataMember(Name = "valid_at", EmitDefaultValue = false)]
        public string ValidAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchMemoryRequest {\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("  FromTime: ").Append(FromTime).Append("\n");
            sb.Append("  GraphDepth: ").Append(GraphDepth).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  MetadataFilter: ").Append(MetadataFilter).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  RerankerType: ").Append(RerankerType).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  SpeakerActorId: ").Append(SpeakerActorId).Append("\n");
            sb.Append("  ToTime: ").Append(ToTime).Append("\n");
            sb.Append("  ValidAt: ").Append(ValidAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // GraphDepth (int) minimum
            if (this.GraphDepth < (int)0)
            {
                yield return new ValidationResult("Invalid value for GraphDepth, must be a value greater than or equal to 0.", new [] { "GraphDepth" });
            }

            // SpeakerActorId (string) maxLength
            if (this.SpeakerActorId != null && this.SpeakerActorId.Length > 64)
            {
                yield return new ValidationResult("Invalid value for SpeakerActorId, length must be less than 64.", new [] { "SpeakerActorId" });
            }

            yield break;
        }
    }

}
