/*
 * smritea SDK API
 *
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Smritea.Internal.Autogen.Client;
using Smritea.Internal.Autogen.Model;

namespace Smritea.Internal.Autogen.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISDKMemoryApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create memory (SDK)
        /// </summary>
        /// <remarks>
        /// Create a new memory with quota and rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Memory creation details</param>
        /// <returns>CreateMemoryResponse</returns>
        CreateMemoryResponse CreateMemory(string xAppID, CreateMemoryRequest request);

        /// <summary>
        /// Create memory (SDK)
        /// </summary>
        /// <remarks>
        /// Create a new memory with quota and rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Memory creation details</param>
        /// <returns>ApiResponse of CreateMemoryResponse</returns>
        ApiResponse<CreateMemoryResponse> CreateMemoryWithHttpInfo(string xAppID, CreateMemoryRequest request);
        /// <summary>
        /// Delete memory (SDK)
        /// </summary>
        /// <remarks>
        /// Delete a memory by ID with rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <returns></returns>
        void DeleteMemory(string xAppID, string memoryId);

        /// <summary>
        /// Delete memory (SDK)
        /// </summary>
        /// <remarks>
        /// Delete a memory by ID with rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteMemoryWithHttpInfo(string xAppID, string memoryId);
        /// <summary>
        /// Get memory by ID (SDK)
        /// </summary>
        /// <remarks>
        /// Get a single memory by ID with rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <returns>MemoryResponse</returns>
        MemoryResponse GetMemory(string xAppID, string memoryId);

        /// <summary>
        /// Get memory by ID (SDK)
        /// </summary>
        /// <remarks>
        /// Get a single memory by ID with rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <returns>ApiResponse of MemoryResponse</returns>
        ApiResponse<MemoryResponse> GetMemoryWithHttpInfo(string xAppID, string memoryId);
        /// <summary>
        /// Search memories (SDK)
        /// </summary>
        /// <remarks>
        /// Search memories with quota and rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Search request details</param>
        /// <returns>SearchMemoriesResponse</returns>
        SearchMemoriesResponse SearchMemories(string xAppID, SearchMemoryRequest request);

        /// <summary>
        /// Search memories (SDK)
        /// </summary>
        /// <remarks>
        /// Search memories with quota and rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Search request details</param>
        /// <returns>ApiResponse of SearchMemoriesResponse</returns>
        ApiResponse<SearchMemoriesResponse> SearchMemoriesWithHttpInfo(string xAppID, SearchMemoryRequest request);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISDKMemoryApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create memory (SDK)
        /// </summary>
        /// <remarks>
        /// Create a new memory with quota and rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Memory creation details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateMemoryResponse</returns>
        System.Threading.Tasks.Task<CreateMemoryResponse> CreateMemoryAsync(string xAppID, CreateMemoryRequest request, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create memory (SDK)
        /// </summary>
        /// <remarks>
        /// Create a new memory with quota and rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Memory creation details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateMemoryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateMemoryResponse>> CreateMemoryWithHttpInfoAsync(string xAppID, CreateMemoryRequest request, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete memory (SDK)
        /// </summary>
        /// <remarks>
        /// Delete a memory by ID with rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteMemoryAsync(string xAppID, string memoryId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete memory (SDK)
        /// </summary>
        /// <remarks>
        /// Delete a memory by ID with rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteMemoryWithHttpInfoAsync(string xAppID, string memoryId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get memory by ID (SDK)
        /// </summary>
        /// <remarks>
        /// Get a single memory by ID with rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MemoryResponse</returns>
        System.Threading.Tasks.Task<MemoryResponse> GetMemoryAsync(string xAppID, string memoryId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get memory by ID (SDK)
        /// </summary>
        /// <remarks>
        /// Get a single memory by ID with rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MemoryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MemoryResponse>> GetMemoryWithHttpInfoAsync(string xAppID, string memoryId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Search memories (SDK)
        /// </summary>
        /// <remarks>
        /// Search memories with quota and rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Search request details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SearchMemoriesResponse</returns>
        System.Threading.Tasks.Task<SearchMemoriesResponse> SearchMemoriesAsync(string xAppID, SearchMemoryRequest request, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Search memories (SDK)
        /// </summary>
        /// <remarks>
        /// Search memories with quota and rate limit enforcement
        /// </remarks>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Search request details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SearchMemoriesResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SearchMemoriesResponse>> SearchMemoriesWithHttpInfoAsync(string xAppID, SearchMemoryRequest request, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISDKMemoryApi : ISDKMemoryApiSync, ISDKMemoryApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SDKMemoryApi : IDisposable, ISDKMemoryApi
    {
        private Smritea.Internal.Autogen.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SDKMemoryApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public SDKMemoryApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SDKMemoryApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public SDKMemoryApi(string basePath)
        {
            this.Configuration = Smritea.Internal.Autogen.Client.Configuration.MergeConfigurations(
                Smritea.Internal.Autogen.Client.GlobalConfiguration.Instance,
                new Smritea.Internal.Autogen.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Smritea.Internal.Autogen.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Smritea.Internal.Autogen.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SDKMemoryApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public SDKMemoryApi(Smritea.Internal.Autogen.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Smritea.Internal.Autogen.Client.Configuration.MergeConfigurations(
                Smritea.Internal.Autogen.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Smritea.Internal.Autogen.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Smritea.Internal.Autogen.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SDKMemoryApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SDKMemoryApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SDKMemoryApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SDKMemoryApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Smritea.Internal.Autogen.Client.Configuration.MergeConfigurations(
                Smritea.Internal.Autogen.Client.GlobalConfiguration.Instance,
                new Smritea.Internal.Autogen.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Smritea.Internal.Autogen.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Smritea.Internal.Autogen.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SDKMemoryApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SDKMemoryApi(HttpClient client, Smritea.Internal.Autogen.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Smritea.Internal.Autogen.Client.Configuration.MergeConfigurations(
                Smritea.Internal.Autogen.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Smritea.Internal.Autogen.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Smritea.Internal.Autogen.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SDKMemoryApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public SDKMemoryApi(Smritea.Internal.Autogen.Client.ISynchronousClient client, Smritea.Internal.Autogen.Client.IAsynchronousClient asyncClient, Smritea.Internal.Autogen.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Smritea.Internal.Autogen.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Smritea.Internal.Autogen.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Smritea.Internal.Autogen.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Smritea.Internal.Autogen.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Smritea.Internal.Autogen.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Smritea.Internal.Autogen.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create memory (SDK) Create a new memory with quota and rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Memory creation details</param>
        /// <returns>CreateMemoryResponse</returns>
        public CreateMemoryResponse CreateMemory(string xAppID, CreateMemoryRequest request)
        {
            Smritea.Internal.Autogen.Client.ApiResponse<CreateMemoryResponse> localVarResponse = CreateMemoryWithHttpInfo(xAppID, request);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create memory (SDK) Create a new memory with quota and rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Memory creation details</param>
        /// <returns>ApiResponse of CreateMemoryResponse</returns>
        public Smritea.Internal.Autogen.Client.ApiResponse<CreateMemoryResponse> CreateMemoryWithHttpInfo(string xAppID, CreateMemoryRequest request)
        {
            // verify the required parameter 'xAppID' is set
            if (xAppID == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'xAppID' when calling SDKMemoryApi->CreateMemory");

            // verify the required parameter 'request' is set
            if (request == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'request' when calling SDKMemoryApi->CreateMemory");

            Smritea.Internal.Autogen.Client.RequestOptions localVarRequestOptions = new Smritea.Internal.Autogen.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.HeaderParameters.Add("X-App-ID", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(xAppID)); // header parameter
            localVarRequestOptions.Data = request;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateMemoryResponse>("/api/v1/sdk/memories", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateMemory", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create memory (SDK) Create a new memory with quota and rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Memory creation details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateMemoryResponse</returns>
        public async System.Threading.Tasks.Task<CreateMemoryResponse> CreateMemoryAsync(string xAppID, CreateMemoryRequest request, System.Threading.CancellationToken cancellationToken = default)
        {
            Smritea.Internal.Autogen.Client.ApiResponse<CreateMemoryResponse> localVarResponse = await CreateMemoryWithHttpInfoAsync(xAppID, request, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create memory (SDK) Create a new memory with quota and rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Memory creation details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateMemoryResponse)</returns>
        public async System.Threading.Tasks.Task<Smritea.Internal.Autogen.Client.ApiResponse<CreateMemoryResponse>> CreateMemoryWithHttpInfoAsync(string xAppID, CreateMemoryRequest request, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'xAppID' is set
            if (xAppID == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'xAppID' when calling SDKMemoryApi->CreateMemory");

            // verify the required parameter 'request' is set
            if (request == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'request' when calling SDKMemoryApi->CreateMemory");


            Smritea.Internal.Autogen.Client.RequestOptions localVarRequestOptions = new Smritea.Internal.Autogen.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.HeaderParameters.Add("X-App-ID", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(xAppID)); // header parameter
            localVarRequestOptions.Data = request;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateMemoryResponse>("/api/v1/sdk/memories", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateMemory", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete memory (SDK) Delete a memory by ID with rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <returns></returns>
        public void DeleteMemory(string xAppID, string memoryId)
        {
            DeleteMemoryWithHttpInfo(xAppID, memoryId);
        }

        /// <summary>
        /// Delete memory (SDK) Delete a memory by ID with rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Smritea.Internal.Autogen.Client.ApiResponse<Object> DeleteMemoryWithHttpInfo(string xAppID, string memoryId)
        {
            // verify the required parameter 'xAppID' is set
            if (xAppID == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'xAppID' when calling SDKMemoryApi->DeleteMemory");

            // verify the required parameter 'memoryId' is set
            if (memoryId == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'memoryId' when calling SDKMemoryApi->DeleteMemory");

            Smritea.Internal.Autogen.Client.RequestOptions localVarRequestOptions = new Smritea.Internal.Autogen.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("memory_id", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(memoryId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("X-App-ID", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(xAppID)); // header parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/v1/sdk/memories/{memory_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteMemory", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete memory (SDK) Delete a memory by ID with rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteMemoryAsync(string xAppID, string memoryId, System.Threading.CancellationToken cancellationToken = default)
        {
            await DeleteMemoryWithHttpInfoAsync(xAppID, memoryId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete memory (SDK) Delete a memory by ID with rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Smritea.Internal.Autogen.Client.ApiResponse<Object>> DeleteMemoryWithHttpInfoAsync(string xAppID, string memoryId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'xAppID' is set
            if (xAppID == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'xAppID' when calling SDKMemoryApi->DeleteMemory");

            // verify the required parameter 'memoryId' is set
            if (memoryId == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'memoryId' when calling SDKMemoryApi->DeleteMemory");


            Smritea.Internal.Autogen.Client.RequestOptions localVarRequestOptions = new Smritea.Internal.Autogen.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("memory_id", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(memoryId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("X-App-ID", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(xAppID)); // header parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api/v1/sdk/memories/{memory_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteMemory", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get memory by ID (SDK) Get a single memory by ID with rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <returns>MemoryResponse</returns>
        public MemoryResponse GetMemory(string xAppID, string memoryId)
        {
            Smritea.Internal.Autogen.Client.ApiResponse<MemoryResponse> localVarResponse = GetMemoryWithHttpInfo(xAppID, memoryId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get memory by ID (SDK) Get a single memory by ID with rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <returns>ApiResponse of MemoryResponse</returns>
        public Smritea.Internal.Autogen.Client.ApiResponse<MemoryResponse> GetMemoryWithHttpInfo(string xAppID, string memoryId)
        {
            // verify the required parameter 'xAppID' is set
            if (xAppID == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'xAppID' when calling SDKMemoryApi->GetMemory");

            // verify the required parameter 'memoryId' is set
            if (memoryId == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'memoryId' when calling SDKMemoryApi->GetMemory");

            Smritea.Internal.Autogen.Client.RequestOptions localVarRequestOptions = new Smritea.Internal.Autogen.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("memory_id", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(memoryId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("X-App-ID", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(xAppID)); // header parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<MemoryResponse>("/api/v1/sdk/memories/{memory_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMemory", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get memory by ID (SDK) Get a single memory by ID with rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MemoryResponse</returns>
        public async System.Threading.Tasks.Task<MemoryResponse> GetMemoryAsync(string xAppID, string memoryId, System.Threading.CancellationToken cancellationToken = default)
        {
            Smritea.Internal.Autogen.Client.ApiResponse<MemoryResponse> localVarResponse = await GetMemoryWithHttpInfoAsync(xAppID, memoryId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get memory by ID (SDK) Get a single memory by ID with rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="memoryId">Memory ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MemoryResponse)</returns>
        public async System.Threading.Tasks.Task<Smritea.Internal.Autogen.Client.ApiResponse<MemoryResponse>> GetMemoryWithHttpInfoAsync(string xAppID, string memoryId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'xAppID' is set
            if (xAppID == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'xAppID' when calling SDKMemoryApi->GetMemory");

            // verify the required parameter 'memoryId' is set
            if (memoryId == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'memoryId' when calling SDKMemoryApi->GetMemory");


            Smritea.Internal.Autogen.Client.RequestOptions localVarRequestOptions = new Smritea.Internal.Autogen.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("memory_id", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(memoryId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("X-App-ID", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(xAppID)); // header parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<MemoryResponse>("/api/v1/sdk/memories/{memory_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMemory", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search memories (SDK) Search memories with quota and rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Search request details</param>
        /// <returns>SearchMemoriesResponse</returns>
        public SearchMemoriesResponse SearchMemories(string xAppID, SearchMemoryRequest request)
        {
            Smritea.Internal.Autogen.Client.ApiResponse<SearchMemoriesResponse> localVarResponse = SearchMemoriesWithHttpInfo(xAppID, request);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search memories (SDK) Search memories with quota and rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Search request details</param>
        /// <returns>ApiResponse of SearchMemoriesResponse</returns>
        public Smritea.Internal.Autogen.Client.ApiResponse<SearchMemoriesResponse> SearchMemoriesWithHttpInfo(string xAppID, SearchMemoryRequest request)
        {
            // verify the required parameter 'xAppID' is set
            if (xAppID == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'xAppID' when calling SDKMemoryApi->SearchMemories");

            // verify the required parameter 'request' is set
            if (request == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'request' when calling SDKMemoryApi->SearchMemories");

            Smritea.Internal.Autogen.Client.RequestOptions localVarRequestOptions = new Smritea.Internal.Autogen.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.HeaderParameters.Add("X-App-ID", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(xAppID)); // header parameter
            localVarRequestOptions.Data = request;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SearchMemoriesResponse>("/api/v1/sdk/memories/search", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SearchMemories", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search memories (SDK) Search memories with quota and rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Search request details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SearchMemoriesResponse</returns>
        public async System.Threading.Tasks.Task<SearchMemoriesResponse> SearchMemoriesAsync(string xAppID, SearchMemoryRequest request, System.Threading.CancellationToken cancellationToken = default)
        {
            Smritea.Internal.Autogen.Client.ApiResponse<SearchMemoriesResponse> localVarResponse = await SearchMemoriesWithHttpInfoAsync(xAppID, request, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search memories (SDK) Search memories with quota and rate limit enforcement
        /// </summary>
        /// <exception cref="Smritea.Internal.Autogen.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAppID">App ID</param>
        /// <param name="request">Search request details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SearchMemoriesResponse)</returns>
        public async System.Threading.Tasks.Task<Smritea.Internal.Autogen.Client.ApiResponse<SearchMemoriesResponse>> SearchMemoriesWithHttpInfoAsync(string xAppID, SearchMemoryRequest request, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'xAppID' is set
            if (xAppID == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'xAppID' when calling SDKMemoryApi->SearchMemories");

            // verify the required parameter 'request' is set
            if (request == null)
                throw new Smritea.Internal.Autogen.Client.ApiException(400, "Missing required parameter 'request' when calling SDKMemoryApi->SearchMemories");


            Smritea.Internal.Autogen.Client.RequestOptions localVarRequestOptions = new Smritea.Internal.Autogen.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Smritea.Internal.Autogen.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.HeaderParameters.Add("X-App-ID", Smritea.Internal.Autogen.Client.ClientUtils.ParameterToString(xAppID)); // header parameter
            localVarRequestOptions.Data = request;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<SearchMemoriesResponse>("/api/v1/sdk/memories/search", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SearchMemories", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
