/*
smritea SDK API

Public SDK API for smritea AI memory system — programmatic memory operations via API key

API version: 1.0.0
Contact: support@smritea.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogen

import (
	"encoding/json"
)

// checks if the PersonaExtractionConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PersonaExtractionConfig{}

// PersonaExtractionConfig struct for PersonaExtractionConfig
type PersonaExtractionConfig struct {
	// ActorTypes filters which actor types to extract personas for (empty = all types). Valid types: user, agent, system
	ActorTypes []string `json:"actor_types,omitempty"`
	// Domains specifies which persona domains to extract. Each domain defines a category of traits (preferences, interests, etc.).
	Domains []PersonaDomainConfig `json:"domains,omitempty"`
	// Enabled controls whether persona extraction is active. When false, no persona traits are extracted from memory content. Unlike Entity/Fact extraction, persona has no multi-pass reflection — it runs a single LLM call.
	Enabled *bool `json:"enabled,omitempty"`
	// Model has no effect today: the model comes from the system AI connection. Reserved for model selection by criteria, allowed only for apps that use their own AI (custom AI / BYOK).
	Model *string `json:"model,omitempty"`
}

// NewPersonaExtractionConfig instantiates a new PersonaExtractionConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPersonaExtractionConfig() *PersonaExtractionConfig {
	this := PersonaExtractionConfig{}
	return &this
}

// NewPersonaExtractionConfigWithDefaults instantiates a new PersonaExtractionConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersonaExtractionConfigWithDefaults() *PersonaExtractionConfig {
	this := PersonaExtractionConfig{}
	return &this
}

// GetActorTypes returns the ActorTypes field value if set, zero value otherwise.
func (o *PersonaExtractionConfig) GetActorTypes() []string {
	if o == nil || IsNil(o.ActorTypes) {
		var ret []string
		return ret
	}
	return o.ActorTypes
}

// GetActorTypesOk returns a tuple with the ActorTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonaExtractionConfig) GetActorTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.ActorTypes) {
		return nil, false
	}
	return o.ActorTypes, true
}

// HasActorTypes returns a boolean if a field has been set.
func (o *PersonaExtractionConfig) HasActorTypes() bool {
	if o != nil && !IsNil(o.ActorTypes) {
		return true
	}

	return false
}

// SetActorTypes gets a reference to the given []string and assigns it to the ActorTypes field.
func (o *PersonaExtractionConfig) SetActorTypes(v []string) {
	o.ActorTypes = v
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *PersonaExtractionConfig) GetDomains() []PersonaDomainConfig {
	if o == nil || IsNil(o.Domains) {
		var ret []PersonaDomainConfig
		return ret
	}
	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonaExtractionConfig) GetDomainsOk() ([]PersonaDomainConfig, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *PersonaExtractionConfig) HasDomains() bool {
	if o != nil && !IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []PersonaDomainConfig and assigns it to the Domains field.
func (o *PersonaExtractionConfig) SetDomains(v []PersonaDomainConfig) {
	o.Domains = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PersonaExtractionConfig) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonaExtractionConfig) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PersonaExtractionConfig) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PersonaExtractionConfig) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *PersonaExtractionConfig) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonaExtractionConfig) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *PersonaExtractionConfig) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *PersonaExtractionConfig) SetModel(v string) {
	o.Model = &v
}

func (o PersonaExtractionConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PersonaExtractionConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActorTypes) {
		toSerialize["actor_types"] = o.ActorTypes
	}
	if !IsNil(o.Domains) {
		toSerialize["domains"] = o.Domains
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	return toSerialize, nil
}

type NullablePersonaExtractionConfig struct {
	value *PersonaExtractionConfig
	isSet bool
}

func (v NullablePersonaExtractionConfig) Get() *PersonaExtractionConfig {
	return v.value
}

func (v *NullablePersonaExtractionConfig) Set(val *PersonaExtractionConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePersonaExtractionConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePersonaExtractionConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePersonaExtractionConfig(val *PersonaExtractionConfig) *NullablePersonaExtractionConfig {
	return &NullablePersonaExtractionConfig{value: val, isSet: true}
}

func (v NullablePersonaExtractionConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePersonaExtractionConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


