/*
smritea SDK API

Public SDK API for smritea AI memory system — programmatic memory operations via API key

API version: 1.0.0
Contact: support@smritea.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogen

import (
	"encoding/json"
)

// checks if the CommondtoMemoryScope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommondtoMemoryScope{}

// CommondtoMemoryScope struct for CommondtoMemoryScope
type CommondtoMemoryScope struct {
	ActorId *string `json:"actor_id,omitempty"`
	ActorName *string `json:"actor_name,omitempty"`
	ActorType *string `json:"actor_type,omitempty"`
	ConversationId *string `json:"conversation_id,omitempty"`
	ConversationMessageId *string `json:"conversation_message_id,omitempty"`
	SourceType *string `json:"source_type,omitempty"`
}

// NewCommondtoMemoryScope instantiates a new CommondtoMemoryScope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommondtoMemoryScope() *CommondtoMemoryScope {
	this := CommondtoMemoryScope{}
	return &this
}

// NewCommondtoMemoryScopeWithDefaults instantiates a new CommondtoMemoryScope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommondtoMemoryScopeWithDefaults() *CommondtoMemoryScope {
	this := CommondtoMemoryScope{}
	return &this
}

// GetActorId returns the ActorId field value if set, zero value otherwise.
func (o *CommondtoMemoryScope) GetActorId() string {
	if o == nil || IsNil(o.ActorId) {
		var ret string
		return ret
	}
	return *o.ActorId
}

// GetActorIdOk returns a tuple with the ActorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommondtoMemoryScope) GetActorIdOk() (*string, bool) {
	if o == nil || IsNil(o.ActorId) {
		return nil, false
	}
	return o.ActorId, true
}

// HasActorId returns a boolean if a field has been set.
func (o *CommondtoMemoryScope) HasActorId() bool {
	if o != nil && !IsNil(o.ActorId) {
		return true
	}

	return false
}

// SetActorId gets a reference to the given string and assigns it to the ActorId field.
func (o *CommondtoMemoryScope) SetActorId(v string) {
	o.ActorId = &v
}

// GetActorName returns the ActorName field value if set, zero value otherwise.
func (o *CommondtoMemoryScope) GetActorName() string {
	if o == nil || IsNil(o.ActorName) {
		var ret string
		return ret
	}
	return *o.ActorName
}

// GetActorNameOk returns a tuple with the ActorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommondtoMemoryScope) GetActorNameOk() (*string, bool) {
	if o == nil || IsNil(o.ActorName) {
		return nil, false
	}
	return o.ActorName, true
}

// HasActorName returns a boolean if a field has been set.
func (o *CommondtoMemoryScope) HasActorName() bool {
	if o != nil && !IsNil(o.ActorName) {
		return true
	}

	return false
}

// SetActorName gets a reference to the given string and assigns it to the ActorName field.
func (o *CommondtoMemoryScope) SetActorName(v string) {
	o.ActorName = &v
}

// GetActorType returns the ActorType field value if set, zero value otherwise.
func (o *CommondtoMemoryScope) GetActorType() string {
	if o == nil || IsNil(o.ActorType) {
		var ret string
		return ret
	}
	return *o.ActorType
}

// GetActorTypeOk returns a tuple with the ActorType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommondtoMemoryScope) GetActorTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ActorType) {
		return nil, false
	}
	return o.ActorType, true
}

// HasActorType returns a boolean if a field has been set.
func (o *CommondtoMemoryScope) HasActorType() bool {
	if o != nil && !IsNil(o.ActorType) {
		return true
	}

	return false
}

// SetActorType gets a reference to the given string and assigns it to the ActorType field.
func (o *CommondtoMemoryScope) SetActorType(v string) {
	o.ActorType = &v
}

// GetConversationId returns the ConversationId field value if set, zero value otherwise.
func (o *CommondtoMemoryScope) GetConversationId() string {
	if o == nil || IsNil(o.ConversationId) {
		var ret string
		return ret
	}
	return *o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommondtoMemoryScope) GetConversationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConversationId) {
		return nil, false
	}
	return o.ConversationId, true
}

// HasConversationId returns a boolean if a field has been set.
func (o *CommondtoMemoryScope) HasConversationId() bool {
	if o != nil && !IsNil(o.ConversationId) {
		return true
	}

	return false
}

// SetConversationId gets a reference to the given string and assigns it to the ConversationId field.
func (o *CommondtoMemoryScope) SetConversationId(v string) {
	o.ConversationId = &v
}

// GetConversationMessageId returns the ConversationMessageId field value if set, zero value otherwise.
func (o *CommondtoMemoryScope) GetConversationMessageId() string {
	if o == nil || IsNil(o.ConversationMessageId) {
		var ret string
		return ret
	}
	return *o.ConversationMessageId
}

// GetConversationMessageIdOk returns a tuple with the ConversationMessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommondtoMemoryScope) GetConversationMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConversationMessageId) {
		return nil, false
	}
	return o.ConversationMessageId, true
}

// HasConversationMessageId returns a boolean if a field has been set.
func (o *CommondtoMemoryScope) HasConversationMessageId() bool {
	if o != nil && !IsNil(o.ConversationMessageId) {
		return true
	}

	return false
}

// SetConversationMessageId gets a reference to the given string and assigns it to the ConversationMessageId field.
func (o *CommondtoMemoryScope) SetConversationMessageId(v string) {
	o.ConversationMessageId = &v
}

// GetSourceType returns the SourceType field value if set, zero value otherwise.
func (o *CommondtoMemoryScope) GetSourceType() string {
	if o == nil || IsNil(o.SourceType) {
		var ret string
		return ret
	}
	return *o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommondtoMemoryScope) GetSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceType) {
		return nil, false
	}
	return o.SourceType, true
}

// HasSourceType returns a boolean if a field has been set.
func (o *CommondtoMemoryScope) HasSourceType() bool {
	if o != nil && !IsNil(o.SourceType) {
		return true
	}

	return false
}

// SetSourceType gets a reference to the given string and assigns it to the SourceType field.
func (o *CommondtoMemoryScope) SetSourceType(v string) {
	o.SourceType = &v
}

func (o CommondtoMemoryScope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommondtoMemoryScope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActorId) {
		toSerialize["actor_id"] = o.ActorId
	}
	if !IsNil(o.ActorName) {
		toSerialize["actor_name"] = o.ActorName
	}
	if !IsNil(o.ActorType) {
		toSerialize["actor_type"] = o.ActorType
	}
	if !IsNil(o.ConversationId) {
		toSerialize["conversation_id"] = o.ConversationId
	}
	if !IsNil(o.ConversationMessageId) {
		toSerialize["conversation_message_id"] = o.ConversationMessageId
	}
	if !IsNil(o.SourceType) {
		toSerialize["source_type"] = o.SourceType
	}
	return toSerialize, nil
}

type NullableCommondtoMemoryScope struct {
	value *CommondtoMemoryScope
	isSet bool
}

func (v NullableCommondtoMemoryScope) Get() *CommondtoMemoryScope {
	return v.value
}

func (v *NullableCommondtoMemoryScope) Set(val *CommondtoMemoryScope) {
	v.value = val
	v.isSet = true
}

func (v NullableCommondtoMemoryScope) IsSet() bool {
	return v.isSet
}

func (v *NullableCommondtoMemoryScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommondtoMemoryScope(val *CommondtoMemoryScope) *NullableCommondtoMemoryScope {
	return &NullableCommondtoMemoryScope{value: val, isSet: true}
}

func (v NullableCommondtoMemoryScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommondtoMemoryScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


