/*
smritea SDK API

Public SDK API for smritea AI memory system — programmatic memory operations via API key

API version: 1.0.0
Contact: support@smritea.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogen

import (
	"encoding/json"
)

// checks if the MemorySearchMemoriesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemorySearchMemoriesResponse{}

// MemorySearchMemoriesResponse struct for MemorySearchMemoriesResponse
type MemorySearchMemoriesResponse struct {
	Memories []MemorySearchMemoryResponse `json:"memories,omitempty"`
}

// NewMemorySearchMemoriesResponse instantiates a new MemorySearchMemoriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemorySearchMemoriesResponse() *MemorySearchMemoriesResponse {
	this := MemorySearchMemoriesResponse{}
	return &this
}

// NewMemorySearchMemoriesResponseWithDefaults instantiates a new MemorySearchMemoriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemorySearchMemoriesResponseWithDefaults() *MemorySearchMemoriesResponse {
	this := MemorySearchMemoriesResponse{}
	return &this
}

// GetMemories returns the Memories field value if set, zero value otherwise.
func (o *MemorySearchMemoriesResponse) GetMemories() []MemorySearchMemoryResponse {
	if o == nil || IsNil(o.Memories) {
		var ret []MemorySearchMemoryResponse
		return ret
	}
	return o.Memories
}

// GetMemoriesOk returns a tuple with the Memories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemorySearchMemoriesResponse) GetMemoriesOk() ([]MemorySearchMemoryResponse, bool) {
	if o == nil || IsNil(o.Memories) {
		return nil, false
	}
	return o.Memories, true
}

// HasMemories returns a boolean if a field has been set.
func (o *MemorySearchMemoriesResponse) HasMemories() bool {
	if o != nil && !IsNil(o.Memories) {
		return true
	}

	return false
}

// SetMemories gets a reference to the given []MemorySearchMemoryResponse and assigns it to the Memories field.
func (o *MemorySearchMemoriesResponse) SetMemories(v []MemorySearchMemoryResponse) {
	o.Memories = v
}

func (o MemorySearchMemoriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemorySearchMemoriesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Memories) {
		toSerialize["memories"] = o.Memories
	}
	return toSerialize, nil
}

type NullableMemorySearchMemoriesResponse struct {
	value *MemorySearchMemoriesResponse
	isSet bool
}

func (v NullableMemorySearchMemoriesResponse) Get() *MemorySearchMemoriesResponse {
	return v.value
}

func (v *NullableMemorySearchMemoriesResponse) Set(val *MemorySearchMemoriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMemorySearchMemoriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMemorySearchMemoriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemorySearchMemoriesResponse(val *MemorySearchMemoriesResponse) *NullableMemorySearchMemoriesResponse {
	return &NullableMemorySearchMemoriesResponse{value: val, isSet: true}
}

func (v NullableMemorySearchMemoriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemorySearchMemoriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


