/*
smritea SDK API

Public SDK API for smritea AI memory system — programmatic memory operations via API key

API version: 1.0.0
Contact: support@smritea.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogen

import (
	"encoding/json"
)

// checks if the Trace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Trace{}

// Trace struct for Trace
type Trace struct {
	// Stages contains the trace for each pipeline stage in execution order.
	Stages []StageTrace `json:"stages,omitempty"`
	// TotalMs is the wall-clock duration of the entire search request in milliseconds.
	TotalMs *int32 `json:"total_ms,omitempty"`
}

// NewTrace instantiates a new Trace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrace() *Trace {
	this := Trace{}
	return &this
}

// NewTraceWithDefaults instantiates a new Trace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTraceWithDefaults() *Trace {
	this := Trace{}
	return &this
}

// GetStages returns the Stages field value if set, zero value otherwise.
func (o *Trace) GetStages() []StageTrace {
	if o == nil || IsNil(o.Stages) {
		var ret []StageTrace
		return ret
	}
	return o.Stages
}

// GetStagesOk returns a tuple with the Stages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Trace) GetStagesOk() ([]StageTrace, bool) {
	if o == nil || IsNil(o.Stages) {
		return nil, false
	}
	return o.Stages, true
}

// HasStages returns a boolean if a field has been set.
func (o *Trace) HasStages() bool {
	if o != nil && !IsNil(o.Stages) {
		return true
	}

	return false
}

// SetStages gets a reference to the given []StageTrace and assigns it to the Stages field.
func (o *Trace) SetStages(v []StageTrace) {
	o.Stages = v
}

// GetTotalMs returns the TotalMs field value if set, zero value otherwise.
func (o *Trace) GetTotalMs() int32 {
	if o == nil || IsNil(o.TotalMs) {
		var ret int32
		return ret
	}
	return *o.TotalMs
}

// GetTotalMsOk returns a tuple with the TotalMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Trace) GetTotalMsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalMs) {
		return nil, false
	}
	return o.TotalMs, true
}

// HasTotalMs returns a boolean if a field has been set.
func (o *Trace) HasTotalMs() bool {
	if o != nil && !IsNil(o.TotalMs) {
		return true
	}

	return false
}

// SetTotalMs gets a reference to the given int32 and assigns it to the TotalMs field.
func (o *Trace) SetTotalMs(v int32) {
	o.TotalMs = &v
}

func (o Trace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Trace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Stages) {
		toSerialize["stages"] = o.Stages
	}
	if !IsNil(o.TotalMs) {
		toSerialize["total_ms"] = o.TotalMs
	}
	return toSerialize, nil
}

type NullableTrace struct {
	value *Trace
	isSet bool
}

func (v NullableTrace) Get() *Trace {
	return v.value
}

func (v *NullableTrace) Set(val *Trace) {
	v.value = val
	v.isSet = true
}

func (v NullableTrace) IsSet() bool {
	return v.isSet
}

func (v *NullableTrace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrace(val *Trace) *NullableTrace {
	return &NullableTrace{value: val, isSet: true}
}

func (v NullableTrace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


