/*
smritea SDK API

Public SDK API for smritea AI memory system — programmatic memory operations via API key

API version: 1.0.0
Contact: support@smritea.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogen

import (
	"encoding/json"
)

// checks if the MemoryCreateMemoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryCreateMemoryResponse{}

// MemoryCreateMemoryResponse struct for MemoryCreateMemoryResponse
type MemoryCreateMemoryResponse struct {
	ExplainTrace *ExplainTrace `json:"explain_trace,omitempty"`
	// ExplicitSkip is true when the LLM intentionally extracted no facts; nothing was stored.
	ExplicitSkip *bool `json:"explicit_skip,omitempty"`
	// FactsExtracted is the number of discrete facts the LLM extracted from the input. 0 when extraction is disabled (NoExtract/quick_search), when extraction fails, when the LLM finds no facts (ExplicitSkip), or when passthrough applies.
	FactsExtracted *int32 `json:"facts_extracted,omitempty"`
	// Memories contains all memories created from the extracted facts. When extraction is disabled or fails, this contains a single memory with the original content. When ExplicitSkip is true (phatic / non-extractable content), this is empty.
	Memories []MemoryMemoryResponse `json:"memories,omitempty"`
	// SkippedCount is the number of facts skipped due to deduplication (exact duplicates).
	SkippedCount *int32 `json:"skipped_count,omitempty"`
	// UpdatedCount is the number of facts that resulted in updates to existing memories.
	UpdatedCount *int32 `json:"updated_count,omitempty"`
}

// NewMemoryCreateMemoryResponse instantiates a new MemoryCreateMemoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryCreateMemoryResponse() *MemoryCreateMemoryResponse {
	this := MemoryCreateMemoryResponse{}
	return &this
}

// NewMemoryCreateMemoryResponseWithDefaults instantiates a new MemoryCreateMemoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryCreateMemoryResponseWithDefaults() *MemoryCreateMemoryResponse {
	this := MemoryCreateMemoryResponse{}
	return &this
}

// GetExplainTrace returns the ExplainTrace field value if set, zero value otherwise.
func (o *MemoryCreateMemoryResponse) GetExplainTrace() ExplainTrace {
	if o == nil || IsNil(o.ExplainTrace) {
		var ret ExplainTrace
		return ret
	}
	return *o.ExplainTrace
}

// GetExplainTraceOk returns a tuple with the ExplainTrace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryCreateMemoryResponse) GetExplainTraceOk() (*ExplainTrace, bool) {
	if o == nil || IsNil(o.ExplainTrace) {
		return nil, false
	}
	return o.ExplainTrace, true
}

// HasExplainTrace returns a boolean if a field has been set.
func (o *MemoryCreateMemoryResponse) HasExplainTrace() bool {
	if o != nil && !IsNil(o.ExplainTrace) {
		return true
	}

	return false
}

// SetExplainTrace gets a reference to the given ExplainTrace and assigns it to the ExplainTrace field.
func (o *MemoryCreateMemoryResponse) SetExplainTrace(v ExplainTrace) {
	o.ExplainTrace = &v
}

// GetExplicitSkip returns the ExplicitSkip field value if set, zero value otherwise.
func (o *MemoryCreateMemoryResponse) GetExplicitSkip() bool {
	if o == nil || IsNil(o.ExplicitSkip) {
		var ret bool
		return ret
	}
	return *o.ExplicitSkip
}

// GetExplicitSkipOk returns a tuple with the ExplicitSkip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryCreateMemoryResponse) GetExplicitSkipOk() (*bool, bool) {
	if o == nil || IsNil(o.ExplicitSkip) {
		return nil, false
	}
	return o.ExplicitSkip, true
}

// HasExplicitSkip returns a boolean if a field has been set.
func (o *MemoryCreateMemoryResponse) HasExplicitSkip() bool {
	if o != nil && !IsNil(o.ExplicitSkip) {
		return true
	}

	return false
}

// SetExplicitSkip gets a reference to the given bool and assigns it to the ExplicitSkip field.
func (o *MemoryCreateMemoryResponse) SetExplicitSkip(v bool) {
	o.ExplicitSkip = &v
}

// GetFactsExtracted returns the FactsExtracted field value if set, zero value otherwise.
func (o *MemoryCreateMemoryResponse) GetFactsExtracted() int32 {
	if o == nil || IsNil(o.FactsExtracted) {
		var ret int32
		return ret
	}
	return *o.FactsExtracted
}

// GetFactsExtractedOk returns a tuple with the FactsExtracted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryCreateMemoryResponse) GetFactsExtractedOk() (*int32, bool) {
	if o == nil || IsNil(o.FactsExtracted) {
		return nil, false
	}
	return o.FactsExtracted, true
}

// HasFactsExtracted returns a boolean if a field has been set.
func (o *MemoryCreateMemoryResponse) HasFactsExtracted() bool {
	if o != nil && !IsNil(o.FactsExtracted) {
		return true
	}

	return false
}

// SetFactsExtracted gets a reference to the given int32 and assigns it to the FactsExtracted field.
func (o *MemoryCreateMemoryResponse) SetFactsExtracted(v int32) {
	o.FactsExtracted = &v
}

// GetMemories returns the Memories field value if set, zero value otherwise.
func (o *MemoryCreateMemoryResponse) GetMemories() []MemoryMemoryResponse {
	if o == nil || IsNil(o.Memories) {
		var ret []MemoryMemoryResponse
		return ret
	}
	return o.Memories
}

// GetMemoriesOk returns a tuple with the Memories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryCreateMemoryResponse) GetMemoriesOk() ([]MemoryMemoryResponse, bool) {
	if o == nil || IsNil(o.Memories) {
		return nil, false
	}
	return o.Memories, true
}

// HasMemories returns a boolean if a field has been set.
func (o *MemoryCreateMemoryResponse) HasMemories() bool {
	if o != nil && !IsNil(o.Memories) {
		return true
	}

	return false
}

// SetMemories gets a reference to the given []MemoryMemoryResponse and assigns it to the Memories field.
func (o *MemoryCreateMemoryResponse) SetMemories(v []MemoryMemoryResponse) {
	o.Memories = v
}

// GetSkippedCount returns the SkippedCount field value if set, zero value otherwise.
func (o *MemoryCreateMemoryResponse) GetSkippedCount() int32 {
	if o == nil || IsNil(o.SkippedCount) {
		var ret int32
		return ret
	}
	return *o.SkippedCount
}

// GetSkippedCountOk returns a tuple with the SkippedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryCreateMemoryResponse) GetSkippedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SkippedCount) {
		return nil, false
	}
	return o.SkippedCount, true
}

// HasSkippedCount returns a boolean if a field has been set.
func (o *MemoryCreateMemoryResponse) HasSkippedCount() bool {
	if o != nil && !IsNil(o.SkippedCount) {
		return true
	}

	return false
}

// SetSkippedCount gets a reference to the given int32 and assigns it to the SkippedCount field.
func (o *MemoryCreateMemoryResponse) SetSkippedCount(v int32) {
	o.SkippedCount = &v
}

// GetUpdatedCount returns the UpdatedCount field value if set, zero value otherwise.
func (o *MemoryCreateMemoryResponse) GetUpdatedCount() int32 {
	if o == nil || IsNil(o.UpdatedCount) {
		var ret int32
		return ret
	}
	return *o.UpdatedCount
}

// GetUpdatedCountOk returns a tuple with the UpdatedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryCreateMemoryResponse) GetUpdatedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.UpdatedCount) {
		return nil, false
	}
	return o.UpdatedCount, true
}

// HasUpdatedCount returns a boolean if a field has been set.
func (o *MemoryCreateMemoryResponse) HasUpdatedCount() bool {
	if o != nil && !IsNil(o.UpdatedCount) {
		return true
	}

	return false
}

// SetUpdatedCount gets a reference to the given int32 and assigns it to the UpdatedCount field.
func (o *MemoryCreateMemoryResponse) SetUpdatedCount(v int32) {
	o.UpdatedCount = &v
}

func (o MemoryCreateMemoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryCreateMemoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExplainTrace) {
		toSerialize["explain_trace"] = o.ExplainTrace
	}
	if !IsNil(o.ExplicitSkip) {
		toSerialize["explicit_skip"] = o.ExplicitSkip
	}
	if !IsNil(o.FactsExtracted) {
		toSerialize["facts_extracted"] = o.FactsExtracted
	}
	if !IsNil(o.Memories) {
		toSerialize["memories"] = o.Memories
	}
	if !IsNil(o.SkippedCount) {
		toSerialize["skipped_count"] = o.SkippedCount
	}
	if !IsNil(o.UpdatedCount) {
		toSerialize["updated_count"] = o.UpdatedCount
	}
	return toSerialize, nil
}

type NullableMemoryCreateMemoryResponse struct {
	value *MemoryCreateMemoryResponse
	isSet bool
}

func (v NullableMemoryCreateMemoryResponse) Get() *MemoryCreateMemoryResponse {
	return v.value
}

func (v *NullableMemoryCreateMemoryResponse) Set(val *MemoryCreateMemoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryCreateMemoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryCreateMemoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryCreateMemoryResponse(val *MemoryCreateMemoryResponse) *NullableMemoryCreateMemoryResponse {
	return &NullableMemoryCreateMemoryResponse{value: val, isSet: true}
}

func (v NullableMemoryCreateMemoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryCreateMemoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


