/*
smritea SDK API

Public SDK API for smritea AI memory system — programmatic memory operations via API key

API version: 1.0.0
Contact: support@smritea.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogen

import (
	"encoding/json"
	"fmt"
)

// ModelEnumsRerankerType the model 'ModelEnumsRerankerType'
type ModelEnumsRerankerType string

// List of model_enums.RerankerType
const (
	RerankerRRF ModelEnumsRerankerType = "rrf"
	RerankerMMR ModelEnumsRerankerType = "mmr"
	RerankerTemporal ModelEnumsRerankerType = "temporal"
	RerankerCrossEncoder ModelEnumsRerankerType = "cross_encoder"
	RerankerNodeDistance ModelEnumsRerankerType = "node_distance"
	RerankerRRFTemporal ModelEnumsRerankerType = "rrf_temporal"
)

// All allowed values of ModelEnumsRerankerType enum
var AllowedModelEnumsRerankerTypeEnumValues = []ModelEnumsRerankerType{
	"rrf",
	"mmr",
	"temporal",
	"cross_encoder",
	"node_distance",
	"rrf_temporal",
}

func (v *ModelEnumsRerankerType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ModelEnumsRerankerType(value)
	for _, existing := range AllowedModelEnumsRerankerTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ModelEnumsRerankerType", value)
}

// NewModelEnumsRerankerTypeFromValue returns a pointer to a valid ModelEnumsRerankerType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewModelEnumsRerankerTypeFromValue(v string) (*ModelEnumsRerankerType, error) {
	ev := ModelEnumsRerankerType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ModelEnumsRerankerType: valid values are %v", v, AllowedModelEnumsRerankerTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ModelEnumsRerankerType) IsValid() bool {
	for _, existing := range AllowedModelEnumsRerankerTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to model_enums.RerankerType value
func (v ModelEnumsRerankerType) Ptr() *ModelEnumsRerankerType {
	return &v
}

type NullableModelEnumsRerankerType struct {
	value *ModelEnumsRerankerType
	isSet bool
}

func (v NullableModelEnumsRerankerType) Get() *ModelEnumsRerankerType {
	return v.value
}

func (v *NullableModelEnumsRerankerType) Set(val *ModelEnumsRerankerType) {
	v.value = val
	v.isSet = true
}

func (v NullableModelEnumsRerankerType) IsSet() bool {
	return v.isSet
}

func (v *NullableModelEnumsRerankerType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelEnumsRerankerType(val *ModelEnumsRerankerType) *NullableModelEnumsRerankerType {
	return &NullableModelEnumsRerankerType{value: val, isSet: true}
}

func (v NullableModelEnumsRerankerType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelEnumsRerankerType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

