/*
smritea SDK API

Public SDK API for smritea AI memory system — programmatic memory operations via API key

API version: 1.0.0
Contact: support@smritea.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PersonaDomainConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PersonaDomainConfig{}

// PersonaDomainConfig struct for PersonaDomainConfig
type PersonaDomainConfig struct {
	// Description describes what kind of traits this domain captures.
	Description *string `json:"description,omitempty"`
	// IsDefault indicates if this domain is included by default.
	IsDefault *bool `json:"is_default,omitempty"`
	// Name is the domain identifier (e.g., \"preferences\", \"interests\", \"demographics\").
	Name string `json:"name"`
	// Traits lists expected trait names for this domain (optional, for LLM guidance).
	Traits []string `json:"traits,omitempty"`
}

type _PersonaDomainConfig PersonaDomainConfig

// NewPersonaDomainConfig instantiates a new PersonaDomainConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPersonaDomainConfig(name string) *PersonaDomainConfig {
	this := PersonaDomainConfig{}
	this.Name = name
	return &this
}

// NewPersonaDomainConfigWithDefaults instantiates a new PersonaDomainConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersonaDomainConfigWithDefaults() *PersonaDomainConfig {
	this := PersonaDomainConfig{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PersonaDomainConfig) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonaDomainConfig) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PersonaDomainConfig) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PersonaDomainConfig) SetDescription(v string) {
	o.Description = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *PersonaDomainConfig) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonaDomainConfig) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *PersonaDomainConfig) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *PersonaDomainConfig) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetName returns the Name field value
func (o *PersonaDomainConfig) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PersonaDomainConfig) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PersonaDomainConfig) SetName(v string) {
	o.Name = v
}

// GetTraits returns the Traits field value if set, zero value otherwise.
func (o *PersonaDomainConfig) GetTraits() []string {
	if o == nil || IsNil(o.Traits) {
		var ret []string
		return ret
	}
	return o.Traits
}

// GetTraitsOk returns a tuple with the Traits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonaDomainConfig) GetTraitsOk() ([]string, bool) {
	if o == nil || IsNil(o.Traits) {
		return nil, false
	}
	return o.Traits, true
}

// HasTraits returns a boolean if a field has been set.
func (o *PersonaDomainConfig) HasTraits() bool {
	if o != nil && !IsNil(o.Traits) {
		return true
	}

	return false
}

// SetTraits gets a reference to the given []string and assigns it to the Traits field.
func (o *PersonaDomainConfig) SetTraits(v []string) {
	o.Traits = v
}

func (o PersonaDomainConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PersonaDomainConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IsDefault) {
		toSerialize["is_default"] = o.IsDefault
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Traits) {
		toSerialize["traits"] = o.Traits
	}
	return toSerialize, nil
}

func (o *PersonaDomainConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPersonaDomainConfig := _PersonaDomainConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPersonaDomainConfig)

	if err != nil {
		return err
	}

	*o = PersonaDomainConfig(varPersonaDomainConfig)

	return err
}

type NullablePersonaDomainConfig struct {
	value *PersonaDomainConfig
	isSet bool
}

func (v NullablePersonaDomainConfig) Get() *PersonaDomainConfig {
	return v.value
}

func (v *NullablePersonaDomainConfig) Set(val *PersonaDomainConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePersonaDomainConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePersonaDomainConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePersonaDomainConfig(val *PersonaDomainConfig) *NullablePersonaDomainConfig {
	return &NullablePersonaDomainConfig{value: val, isSet: true}
}

func (v NullablePersonaDomainConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePersonaDomainConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


