/*
smritea SDK API

Public SDK API for smritea AI memory system — programmatic memory operations via API key

API version: 1.0.0
Contact: support@smritea.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogen

import (
	"encoding/json"
)

// checks if the EntityExtractionConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityExtractionConfig{}

// EntityExtractionConfig struct for EntityExtractionConfig
type EntityExtractionConfig struct {
	// ContextWindow is the number of previous messages to include in context. Only used when EnableContext is true. 0 means use default (10 messages).
	ContextWindow *int32 `json:"context_window,omitempty"`
	// EnableContext enables context-aware extraction using conversation history. When true, extraction considers previous messages in the conversation for better entity resolution and relationship detection.
	EnableContext *bool `json:"enable_context,omitempty"`
	// EntityTypes filters which entity types to extract (empty = all types). Valid types: person, organization, concept, location, event, product, other
	EntityTypes []string `json:"entity_types,omitempty"`
	// FallbackMessages is the minimum number of messages to include even if the conversation is shorter than ContextWindow. Prevents empty context.
	FallbackMessages *int32 `json:"fallback_messages,omitempty"`
	// MaxPasses controls how many extraction passes to perform. -1 = explicitly skip entity extraction (sentinel value). 0 = not specified (Go zero value), use default. 1-5 = run N extraction passes. Multiple passes can improve extraction quality but increase cost and latency.
	MaxPasses *int32 `json:"max_passes,omitempty"`
	// MaxTokens is the maximum completion tokens for LLM responses. 0 = not set (use default). Higher values allow more entities but increase cost. TODO(https://linear.app/bityantriki/issue/BIT-83): revert gte=0 to gte=100 once pedantigo applies defaults to nested structs during Validate()
	MaxTokens *int32 `json:"max_tokens,omitempty"`
	// MinConfidence is the minimum confidence threshold for extracted entities (0.0 to 1.0). Entities below this threshold are filtered out.
	MinConfidence *float32 `json:"min_confidence,omitempty"`
	// Model is the LLM model to use (empty = use provider default). Examples: \"gpt-4\", \"gpt-3.5-turbo\", \"llama-3.3-70b-versatile\"
	Model *string `json:"model,omitempty"`
	// Temperature controls LLM randomness (0.0 = deterministic, higher = creative). For extraction, lower values (0.0-0.3) are recommended for consistency.
	Temperature *float32 `json:"temperature,omitempty"`
}

// NewEntityExtractionConfig instantiates a new EntityExtractionConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityExtractionConfig() *EntityExtractionConfig {
	this := EntityExtractionConfig{}
	return &this
}

// NewEntityExtractionConfigWithDefaults instantiates a new EntityExtractionConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityExtractionConfigWithDefaults() *EntityExtractionConfig {
	this := EntityExtractionConfig{}
	return &this
}

// GetContextWindow returns the ContextWindow field value if set, zero value otherwise.
func (o *EntityExtractionConfig) GetContextWindow() int32 {
	if o == nil || IsNil(o.ContextWindow) {
		var ret int32
		return ret
	}
	return *o.ContextWindow
}

// GetContextWindowOk returns a tuple with the ContextWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityExtractionConfig) GetContextWindowOk() (*int32, bool) {
	if o == nil || IsNil(o.ContextWindow) {
		return nil, false
	}
	return o.ContextWindow, true
}

// HasContextWindow returns a boolean if a field has been set.
func (o *EntityExtractionConfig) HasContextWindow() bool {
	if o != nil && !IsNil(o.ContextWindow) {
		return true
	}

	return false
}

// SetContextWindow gets a reference to the given int32 and assigns it to the ContextWindow field.
func (o *EntityExtractionConfig) SetContextWindow(v int32) {
	o.ContextWindow = &v
}

// GetEnableContext returns the EnableContext field value if set, zero value otherwise.
func (o *EntityExtractionConfig) GetEnableContext() bool {
	if o == nil || IsNil(o.EnableContext) {
		var ret bool
		return ret
	}
	return *o.EnableContext
}

// GetEnableContextOk returns a tuple with the EnableContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityExtractionConfig) GetEnableContextOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableContext) {
		return nil, false
	}
	return o.EnableContext, true
}

// HasEnableContext returns a boolean if a field has been set.
func (o *EntityExtractionConfig) HasEnableContext() bool {
	if o != nil && !IsNil(o.EnableContext) {
		return true
	}

	return false
}

// SetEnableContext gets a reference to the given bool and assigns it to the EnableContext field.
func (o *EntityExtractionConfig) SetEnableContext(v bool) {
	o.EnableContext = &v
}

// GetEntityTypes returns the EntityTypes field value if set, zero value otherwise.
func (o *EntityExtractionConfig) GetEntityTypes() []string {
	if o == nil || IsNil(o.EntityTypes) {
		var ret []string
		return ret
	}
	return o.EntityTypes
}

// GetEntityTypesOk returns a tuple with the EntityTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityExtractionConfig) GetEntityTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.EntityTypes) {
		return nil, false
	}
	return o.EntityTypes, true
}

// HasEntityTypes returns a boolean if a field has been set.
func (o *EntityExtractionConfig) HasEntityTypes() bool {
	if o != nil && !IsNil(o.EntityTypes) {
		return true
	}

	return false
}

// SetEntityTypes gets a reference to the given []string and assigns it to the EntityTypes field.
func (o *EntityExtractionConfig) SetEntityTypes(v []string) {
	o.EntityTypes = v
}

// GetFallbackMessages returns the FallbackMessages field value if set, zero value otherwise.
func (o *EntityExtractionConfig) GetFallbackMessages() int32 {
	if o == nil || IsNil(o.FallbackMessages) {
		var ret int32
		return ret
	}
	return *o.FallbackMessages
}

// GetFallbackMessagesOk returns a tuple with the FallbackMessages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityExtractionConfig) GetFallbackMessagesOk() (*int32, bool) {
	if o == nil || IsNil(o.FallbackMessages) {
		return nil, false
	}
	return o.FallbackMessages, true
}

// HasFallbackMessages returns a boolean if a field has been set.
func (o *EntityExtractionConfig) HasFallbackMessages() bool {
	if o != nil && !IsNil(o.FallbackMessages) {
		return true
	}

	return false
}

// SetFallbackMessages gets a reference to the given int32 and assigns it to the FallbackMessages field.
func (o *EntityExtractionConfig) SetFallbackMessages(v int32) {
	o.FallbackMessages = &v
}

// GetMaxPasses returns the MaxPasses field value if set, zero value otherwise.
func (o *EntityExtractionConfig) GetMaxPasses() int32 {
	if o == nil || IsNil(o.MaxPasses) {
		var ret int32
		return ret
	}
	return *o.MaxPasses
}

// GetMaxPassesOk returns a tuple with the MaxPasses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityExtractionConfig) GetMaxPassesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxPasses) {
		return nil, false
	}
	return o.MaxPasses, true
}

// HasMaxPasses returns a boolean if a field has been set.
func (o *EntityExtractionConfig) HasMaxPasses() bool {
	if o != nil && !IsNil(o.MaxPasses) {
		return true
	}

	return false
}

// SetMaxPasses gets a reference to the given int32 and assigns it to the MaxPasses field.
func (o *EntityExtractionConfig) SetMaxPasses(v int32) {
	o.MaxPasses = &v
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (o *EntityExtractionConfig) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens) {
		var ret int32
		return ret
	}
	return *o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityExtractionConfig) GetMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokens) {
		return nil, false
	}
	return o.MaxTokens, true
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *EntityExtractionConfig) HasMaxTokens() bool {
	if o != nil && !IsNil(o.MaxTokens) {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given int32 and assigns it to the MaxTokens field.
func (o *EntityExtractionConfig) SetMaxTokens(v int32) {
	o.MaxTokens = &v
}

// GetMinConfidence returns the MinConfidence field value if set, zero value otherwise.
func (o *EntityExtractionConfig) GetMinConfidence() float32 {
	if o == nil || IsNil(o.MinConfidence) {
		var ret float32
		return ret
	}
	return *o.MinConfidence
}

// GetMinConfidenceOk returns a tuple with the MinConfidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityExtractionConfig) GetMinConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.MinConfidence) {
		return nil, false
	}
	return o.MinConfidence, true
}

// HasMinConfidence returns a boolean if a field has been set.
func (o *EntityExtractionConfig) HasMinConfidence() bool {
	if o != nil && !IsNil(o.MinConfidence) {
		return true
	}

	return false
}

// SetMinConfidence gets a reference to the given float32 and assigns it to the MinConfidence field.
func (o *EntityExtractionConfig) SetMinConfidence(v float32) {
	o.MinConfidence = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *EntityExtractionConfig) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityExtractionConfig) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *EntityExtractionConfig) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *EntityExtractionConfig) SetModel(v string) {
	o.Model = &v
}

// GetTemperature returns the Temperature field value if set, zero value otherwise.
func (o *EntityExtractionConfig) GetTemperature() float32 {
	if o == nil || IsNil(o.Temperature) {
		var ret float32
		return ret
	}
	return *o.Temperature
}

// GetTemperatureOk returns a tuple with the Temperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityExtractionConfig) GetTemperatureOk() (*float32, bool) {
	if o == nil || IsNil(o.Temperature) {
		return nil, false
	}
	return o.Temperature, true
}

// HasTemperature returns a boolean if a field has been set.
func (o *EntityExtractionConfig) HasTemperature() bool {
	if o != nil && !IsNil(o.Temperature) {
		return true
	}

	return false
}

// SetTemperature gets a reference to the given float32 and assigns it to the Temperature field.
func (o *EntityExtractionConfig) SetTemperature(v float32) {
	o.Temperature = &v
}

func (o EntityExtractionConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityExtractionConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContextWindow) {
		toSerialize["context_window"] = o.ContextWindow
	}
	if !IsNil(o.EnableContext) {
		toSerialize["enable_context"] = o.EnableContext
	}
	if !IsNil(o.EntityTypes) {
		toSerialize["entity_types"] = o.EntityTypes
	}
	if !IsNil(o.FallbackMessages) {
		toSerialize["fallback_messages"] = o.FallbackMessages
	}
	if !IsNil(o.MaxPasses) {
		toSerialize["max_passes"] = o.MaxPasses
	}
	if !IsNil(o.MaxTokens) {
		toSerialize["max_tokens"] = o.MaxTokens
	}
	if !IsNil(o.MinConfidence) {
		toSerialize["min_confidence"] = o.MinConfidence
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Temperature) {
		toSerialize["temperature"] = o.Temperature
	}
	return toSerialize, nil
}

type NullableEntityExtractionConfig struct {
	value *EntityExtractionConfig
	isSet bool
}

func (v NullableEntityExtractionConfig) Get() *EntityExtractionConfig {
	return v.value
}

func (v *NullableEntityExtractionConfig) Set(val *EntityExtractionConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityExtractionConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityExtractionConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityExtractionConfig(val *EntityExtractionConfig) *NullableEntityExtractionConfig {
	return &NullableEntityExtractionConfig{value: val, isSet: true}
}

func (v NullableEntityExtractionConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityExtractionConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


