/*
smritea SDK API

Public SDK API for smritea AI memory system — programmatic memory operations via API key

API version: 1.0.0
Contact: support@smritea.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogen

import (
	"encoding/json"
)

// checks if the ErrorsAppError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorsAppError{}

// ErrorsAppError struct for ErrorsAppError
type ErrorsAppError struct {
	Code *ErrorsErrorCode `json:"code,omitempty"`
	Details *string `json:"details,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewErrorsAppError instantiates a new ErrorsAppError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorsAppError() *ErrorsAppError {
	this := ErrorsAppError{}
	return &this
}

// NewErrorsAppErrorWithDefaults instantiates a new ErrorsAppError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorsAppErrorWithDefaults() *ErrorsAppError {
	this := ErrorsAppError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ErrorsAppError) GetCode() ErrorsErrorCode {
	if o == nil || IsNil(o.Code) {
		var ret ErrorsErrorCode
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorsAppError) GetCodeOk() (*ErrorsErrorCode, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ErrorsAppError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given ErrorsErrorCode and assigns it to the Code field.
func (o *ErrorsAppError) SetCode(v ErrorsErrorCode) {
	o.Code = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *ErrorsAppError) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorsAppError) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *ErrorsAppError) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *ErrorsAppError) SetDetails(v string) {
	o.Details = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ErrorsAppError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorsAppError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ErrorsAppError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ErrorsAppError) SetMessage(v string) {
	o.Message = &v
}

func (o ErrorsAppError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorsAppError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableErrorsAppError struct {
	value *ErrorsAppError
	isSet bool
}

func (v NullableErrorsAppError) Get() *ErrorsAppError {
	return v.value
}

func (v *NullableErrorsAppError) Set(val *ErrorsAppError) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorsAppError) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorsAppError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorsAppError(val *ErrorsAppError) *NullableErrorsAppError {
	return &NullableErrorsAppError{value: val, isSet: true}
}

func (v NullableErrorsAppError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorsAppError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


