/*
smritea SDK API

Public SDK API for smritea AI memory system — programmatic memory operations via API key

API version: 1.0.0
Contact: support@smritea.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchMemoryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchMemoryRequest{}

// SearchMemoryRequest struct for SearchMemoryRequest
type SearchMemoryRequest struct {
	AppId string `json:"app_id"`
	// FromTime filters memories that overlap with time range [FromTime, ToTime] (ISO 8601 format). Must be used together with ToTime.
	FromTime *string `json:"from_time,omitempty"`
	// 0=use app config, 1-5=override traversal depth
	GraphDepth *int32 `json:"graph_depth,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	// MetadataFilter filters memories by user-provided key-value metadata. Only memories whose metadata contains ALL specified key-value pairs are returned.
	MetadataFilter map[string]interface{} `json:"metadata_filter,omitempty"`
	Method *SearchMethod `json:"method,omitempty"`
	Query string `json:"query"`
	// RerankerType overrides the reranker for this request (optional). If nil, uses app config reranker. Only applies to deep_search method.
	RerankerType *RerankerType `json:"reranker_type,omitempty"`
	// Scope groups actor, conversation, and source filtering fields. Zero-value fields mean \"no filter\" (searches across all).
	Scope *MemoryScope `json:"scope,omitempty"`
	// 0=no filtering (pipeline uses RRF scores, not cosine similarity)
	Threshold *float32 `json:"threshold,omitempty"`
	// ToTime is the end of the time range filter (ISO 8601 format). Must be used together with FromTime.
	ToTime *string `json:"to_time,omitempty"`
	// ValidAt filters memories valid at a specific point in time (ISO 8601 format). A memory is valid if: active_from <= ValidAt AND (active_to is null OR active_to >= ValidAt) Mutually exclusive with FromTime/ToTime.
	ValidAt *string `json:"valid_at,omitempty"`
}

type _SearchMemoryRequest SearchMemoryRequest

// NewSearchMemoryRequest instantiates a new SearchMemoryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchMemoryRequest(appId string, query string) *SearchMemoryRequest {
	this := SearchMemoryRequest{}
	this.AppId = appId
	this.Query = query
	return &this
}

// NewSearchMemoryRequestWithDefaults instantiates a new SearchMemoryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchMemoryRequestWithDefaults() *SearchMemoryRequest {
	this := SearchMemoryRequest{}
	return &this
}

// GetAppId returns the AppId field value
func (o *SearchMemoryRequest) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *SearchMemoryRequest) SetAppId(v string) {
	o.AppId = v
}

// GetFromTime returns the FromTime field value if set, zero value otherwise.
func (o *SearchMemoryRequest) GetFromTime() string {
	if o == nil || IsNil(o.FromTime) {
		var ret string
		return ret
	}
	return *o.FromTime
}

// GetFromTimeOk returns a tuple with the FromTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetFromTimeOk() (*string, bool) {
	if o == nil || IsNil(o.FromTime) {
		return nil, false
	}
	return o.FromTime, true
}

// HasFromTime returns a boolean if a field has been set.
func (o *SearchMemoryRequest) HasFromTime() bool {
	if o != nil && !IsNil(o.FromTime) {
		return true
	}

	return false
}

// SetFromTime gets a reference to the given string and assigns it to the FromTime field.
func (o *SearchMemoryRequest) SetFromTime(v string) {
	o.FromTime = &v
}

// GetGraphDepth returns the GraphDepth field value if set, zero value otherwise.
func (o *SearchMemoryRequest) GetGraphDepth() int32 {
	if o == nil || IsNil(o.GraphDepth) {
		var ret int32
		return ret
	}
	return *o.GraphDepth
}

// GetGraphDepthOk returns a tuple with the GraphDepth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetGraphDepthOk() (*int32, bool) {
	if o == nil || IsNil(o.GraphDepth) {
		return nil, false
	}
	return o.GraphDepth, true
}

// HasGraphDepth returns a boolean if a field has been set.
func (o *SearchMemoryRequest) HasGraphDepth() bool {
	if o != nil && !IsNil(o.GraphDepth) {
		return true
	}

	return false
}

// SetGraphDepth gets a reference to the given int32 and assigns it to the GraphDepth field.
func (o *SearchMemoryRequest) SetGraphDepth(v int32) {
	o.GraphDepth = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *SearchMemoryRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *SearchMemoryRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *SearchMemoryRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetMetadataFilter returns the MetadataFilter field value if set, zero value otherwise.
func (o *SearchMemoryRequest) GetMetadataFilter() map[string]interface{} {
	if o == nil || IsNil(o.MetadataFilter) {
		var ret map[string]interface{}
		return ret
	}
	return o.MetadataFilter
}

// GetMetadataFilterOk returns a tuple with the MetadataFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetMetadataFilterOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.MetadataFilter) {
		return map[string]interface{}{}, false
	}
	return o.MetadataFilter, true
}

// HasMetadataFilter returns a boolean if a field has been set.
func (o *SearchMemoryRequest) HasMetadataFilter() bool {
	if o != nil && !IsNil(o.MetadataFilter) {
		return true
	}

	return false
}

// SetMetadataFilter gets a reference to the given map[string]interface{} and assigns it to the MetadataFilter field.
func (o *SearchMemoryRequest) SetMetadataFilter(v map[string]interface{}) {
	o.MetadataFilter = v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *SearchMemoryRequest) GetMethod() SearchMethod {
	if o == nil || IsNil(o.Method) {
		var ret SearchMethod
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetMethodOk() (*SearchMethod, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *SearchMemoryRequest) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given SearchMethod and assigns it to the Method field.
func (o *SearchMemoryRequest) SetMethod(v SearchMethod) {
	o.Method = &v
}

// GetQuery returns the Query field value
func (o *SearchMemoryRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *SearchMemoryRequest) SetQuery(v string) {
	o.Query = v
}

// GetRerankerType returns the RerankerType field value if set, zero value otherwise.
func (o *SearchMemoryRequest) GetRerankerType() RerankerType {
	if o == nil || IsNil(o.RerankerType) {
		var ret RerankerType
		return ret
	}
	return *o.RerankerType
}

// GetRerankerTypeOk returns a tuple with the RerankerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetRerankerTypeOk() (*RerankerType, bool) {
	if o == nil || IsNil(o.RerankerType) {
		return nil, false
	}
	return o.RerankerType, true
}

// HasRerankerType returns a boolean if a field has been set.
func (o *SearchMemoryRequest) HasRerankerType() bool {
	if o != nil && !IsNil(o.RerankerType) {
		return true
	}

	return false
}

// SetRerankerType gets a reference to the given RerankerType and assigns it to the RerankerType field.
func (o *SearchMemoryRequest) SetRerankerType(v RerankerType) {
	o.RerankerType = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *SearchMemoryRequest) GetScope() MemoryScope {
	if o == nil || IsNil(o.Scope) {
		var ret MemoryScope
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetScopeOk() (*MemoryScope, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *SearchMemoryRequest) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given MemoryScope and assigns it to the Scope field.
func (o *SearchMemoryRequest) SetScope(v MemoryScope) {
	o.Scope = &v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *SearchMemoryRequest) GetThreshold() float32 {
	if o == nil || IsNil(o.Threshold) {
		var ret float32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetThresholdOk() (*float32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *SearchMemoryRequest) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given float32 and assigns it to the Threshold field.
func (o *SearchMemoryRequest) SetThreshold(v float32) {
	o.Threshold = &v
}

// GetToTime returns the ToTime field value if set, zero value otherwise.
func (o *SearchMemoryRequest) GetToTime() string {
	if o == nil || IsNil(o.ToTime) {
		var ret string
		return ret
	}
	return *o.ToTime
}

// GetToTimeOk returns a tuple with the ToTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetToTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ToTime) {
		return nil, false
	}
	return o.ToTime, true
}

// HasToTime returns a boolean if a field has been set.
func (o *SearchMemoryRequest) HasToTime() bool {
	if o != nil && !IsNil(o.ToTime) {
		return true
	}

	return false
}

// SetToTime gets a reference to the given string and assigns it to the ToTime field.
func (o *SearchMemoryRequest) SetToTime(v string) {
	o.ToTime = &v
}

// GetValidAt returns the ValidAt field value if set, zero value otherwise.
func (o *SearchMemoryRequest) GetValidAt() string {
	if o == nil || IsNil(o.ValidAt) {
		var ret string
		return ret
	}
	return *o.ValidAt
}

// GetValidAtOk returns a tuple with the ValidAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMemoryRequest) GetValidAtOk() (*string, bool) {
	if o == nil || IsNil(o.ValidAt) {
		return nil, false
	}
	return o.ValidAt, true
}

// HasValidAt returns a boolean if a field has been set.
func (o *SearchMemoryRequest) HasValidAt() bool {
	if o != nil && !IsNil(o.ValidAt) {
		return true
	}

	return false
}

// SetValidAt gets a reference to the given string and assigns it to the ValidAt field.
func (o *SearchMemoryRequest) SetValidAt(v string) {
	o.ValidAt = &v
}

func (o SearchMemoryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchMemoryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["app_id"] = o.AppId
	if !IsNil(o.FromTime) {
		toSerialize["from_time"] = o.FromTime
	}
	if !IsNil(o.GraphDepth) {
		toSerialize["graph_depth"] = o.GraphDepth
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.MetadataFilter) {
		toSerialize["metadata_filter"] = o.MetadataFilter
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	toSerialize["query"] = o.Query
	if !IsNil(o.RerankerType) {
		toSerialize["reranker_type"] = o.RerankerType
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	if !IsNil(o.ToTime) {
		toSerialize["to_time"] = o.ToTime
	}
	if !IsNil(o.ValidAt) {
		toSerialize["valid_at"] = o.ValidAt
	}
	return toSerialize, nil
}

func (o *SearchMemoryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"app_id",
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchMemoryRequest := _SearchMemoryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchMemoryRequest)

	if err != nil {
		return err
	}

	*o = SearchMemoryRequest(varSearchMemoryRequest)

	return err
}

type NullableSearchMemoryRequest struct {
	value *SearchMemoryRequest
	isSet bool
}

func (v NullableSearchMemoryRequest) Get() *SearchMemoryRequest {
	return v.value
}

func (v *NullableSearchMemoryRequest) Set(val *SearchMemoryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchMemoryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchMemoryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchMemoryRequest(val *SearchMemoryRequest) *NullableSearchMemoryRequest {
	return &NullableSearchMemoryRequest{value: val, isSet: true}
}

func (v NullableSearchMemoryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchMemoryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


