/*
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ai.smritea.sdk._internal.autogen.model;

import ai.smritea.sdk._internal.autogen.ApiClient;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/** CommondtoEntityExtractionConfig */
@JsonPropertyOrder({
  CommondtoEntityExtractionConfig.JSON_PROPERTY_CONTEXT_WINDOW,
  CommondtoEntityExtractionConfig.JSON_PROPERTY_ENABLE_CONTEXT,
  CommondtoEntityExtractionConfig.JSON_PROPERTY_ENTITY_TYPES,
  CommondtoEntityExtractionConfig.JSON_PROPERTY_FALLBACK_MESSAGES,
  CommondtoEntityExtractionConfig.JSON_PROPERTY_MAX_PASSES,
  CommondtoEntityExtractionConfig.JSON_PROPERTY_MAX_TOKENS,
  CommondtoEntityExtractionConfig.JSON_PROPERTY_MIN_CONFIDENCE,
  CommondtoEntityExtractionConfig.JSON_PROPERTY_MODEL,
  CommondtoEntityExtractionConfig.JSON_PROPERTY_TEMPERATURE
})
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-03-05T18:33:01.293352+05:30[Asia/Kolkata]",
    comments = "Generator version: 7.19.0")
public class CommondtoEntityExtractionConfig {
  public static final String JSON_PROPERTY_CONTEXT_WINDOW = "context_window";
  @javax.annotation.Nullable private Integer contextWindow;

  public static final String JSON_PROPERTY_ENABLE_CONTEXT = "enable_context";
  @javax.annotation.Nullable private Boolean enableContext;

  public static final String JSON_PROPERTY_ENTITY_TYPES = "entity_types";
  @javax.annotation.Nullable private List<String> entityTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_FALLBACK_MESSAGES = "fallback_messages";
  @javax.annotation.Nullable private Integer fallbackMessages;

  public static final String JSON_PROPERTY_MAX_PASSES = "max_passes";
  @javax.annotation.Nullable private Integer maxPasses;

  public static final String JSON_PROPERTY_MAX_TOKENS = "max_tokens";
  @javax.annotation.Nullable private Integer maxTokens;

  public static final String JSON_PROPERTY_MIN_CONFIDENCE = "min_confidence";
  @javax.annotation.Nullable private BigDecimal minConfidence;

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nullable private String model;

  public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
  @javax.annotation.Nullable private BigDecimal temperature;

  public CommondtoEntityExtractionConfig() {}

  public CommondtoEntityExtractionConfig contextWindow(
      @javax.annotation.Nullable Integer contextWindow) {
    this.contextWindow = contextWindow;
    return this;
  }

  /**
   * ContextWindow is the number of previous messages to include in context. Only used when
   * EnableContext is true. 0 means use default (10 messages).
   *
   * @return contextWindow
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTEXT_WINDOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getContextWindow() {
    return contextWindow;
  }

  @JsonProperty(value = JSON_PROPERTY_CONTEXT_WINDOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContextWindow(@javax.annotation.Nullable Integer contextWindow) {
    this.contextWindow = contextWindow;
  }

  public CommondtoEntityExtractionConfig enableContext(
      @javax.annotation.Nullable Boolean enableContext) {
    this.enableContext = enableContext;
    return this;
  }

  /**
   * EnableContext enables context-aware extraction using conversation history. When true,
   * extraction considers previous messages in the conversation for better entity resolution and
   * relationship detection.
   *
   * @return enableContext
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLE_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEnableContext() {
    return enableContext;
  }

  @JsonProperty(value = JSON_PROPERTY_ENABLE_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnableContext(@javax.annotation.Nullable Boolean enableContext) {
    this.enableContext = enableContext;
  }

  public CommondtoEntityExtractionConfig entityTypes(
      @javax.annotation.Nullable List<String> entityTypes) {
    this.entityTypes = entityTypes;
    return this;
  }

  public CommondtoEntityExtractionConfig addEntityTypesItem(String entityTypesItem) {
    if (this.entityTypes == null) {
      this.entityTypes = new ArrayList<>();
    }
    this.entityTypes.add(entityTypesItem);
    return this;
  }

  /**
   * EntityTypes filters which entity types to extract (empty &#x3D; all types). Valid types:
   * person, organization, concept, location, event, product, other
   *
   * @return entityTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTITY_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getEntityTypes() {
    return entityTypes;
  }

  @JsonProperty(value = JSON_PROPERTY_ENTITY_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityTypes(@javax.annotation.Nullable List<String> entityTypes) {
    this.entityTypes = entityTypes;
  }

  public CommondtoEntityExtractionConfig fallbackMessages(
      @javax.annotation.Nullable Integer fallbackMessages) {
    this.fallbackMessages = fallbackMessages;
    return this;
  }

  /**
   * FallbackMessages is the minimum number of messages to include even if the conversation is
   * shorter than ContextWindow. Prevents empty context.
   *
   * @return fallbackMessages
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FALLBACK_MESSAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFallbackMessages() {
    return fallbackMessages;
  }

  @JsonProperty(value = JSON_PROPERTY_FALLBACK_MESSAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFallbackMessages(@javax.annotation.Nullable Integer fallbackMessages) {
    this.fallbackMessages = fallbackMessages;
  }

  public CommondtoEntityExtractionConfig maxPasses(@javax.annotation.Nullable Integer maxPasses) {
    this.maxPasses = maxPasses;
    return this;
  }

  /**
   * MaxPasses controls how many extraction passes to perform. -1 &#x3D; explicitly skip entity
   * extraction (sentinel value). 0 &#x3D; not specified (Go zero value), use default. 1-5 &#x3D;
   * run N extraction passes. Multiple passes can improve extraction quality but increase cost and
   * latency.
   *
   * @return maxPasses
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_PASSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxPasses() {
    return maxPasses;
  }

  @JsonProperty(value = JSON_PROPERTY_MAX_PASSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxPasses(@javax.annotation.Nullable Integer maxPasses) {
    this.maxPasses = maxPasses;
  }

  public CommondtoEntityExtractionConfig maxTokens(@javax.annotation.Nullable Integer maxTokens) {
    this.maxTokens = maxTokens;
    return this;
  }

  /**
   * MaxTokens is the maximum completion tokens for LLM responses. 0 &#x3D; not set (use default).
   * Higher values allow more entities but increase cost.
   * TODO(https://linear.app/bityantriki/issue/BIT-83): revert gte&#x3D;0 to gte&#x3D;100 once
   * pedantigo applies defaults to nested structs during Validate()
   *
   * @return maxTokens
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxTokens() {
    return maxTokens;
  }

  @JsonProperty(value = JSON_PROPERTY_MAX_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxTokens(@javax.annotation.Nullable Integer maxTokens) {
    this.maxTokens = maxTokens;
  }

  public CommondtoEntityExtractionConfig minConfidence(
      @javax.annotation.Nullable BigDecimal minConfidence) {
    this.minConfidence = minConfidence;
    return this;
  }

  /**
   * MinConfidence is the minimum confidence threshold for extracted entities (0.0 to 1.0). Entities
   * below this threshold are filtered out.
   *
   * @return minConfidence
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MIN_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getMinConfidence() {
    return minConfidence;
  }

  @JsonProperty(value = JSON_PROPERTY_MIN_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinConfidence(@javax.annotation.Nullable BigDecimal minConfidence) {
    this.minConfidence = minConfidence;
  }

  public CommondtoEntityExtractionConfig model(@javax.annotation.Nullable String model) {
    this.model = model;
    return this;
  }

  /**
   * Model is the LLM model to use (empty &#x3D; use provider default). Examples:
   * \&quot;gpt-4\&quot;, \&quot;gpt-3.5-turbo\&quot;, \&quot;llama-3.3-70b-versatile\&quot;
   *
   * @return model
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getModel() {
    return model;
  }

  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(@javax.annotation.Nullable String model) {
    this.model = model;
  }

  public CommondtoEntityExtractionConfig temperature(
      @javax.annotation.Nullable BigDecimal temperature) {
    this.temperature = temperature;
    return this;
  }

  /**
   * Temperature controls LLM randomness (0.0 &#x3D; deterministic, higher &#x3D; creative). For
   * extraction, lower values (0.0-0.3) are recommended for consistency.
   *
   * @return temperature
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTemperature() {
    return temperature;
  }

  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemperature(@javax.annotation.Nullable BigDecimal temperature) {
    this.temperature = temperature;
  }

  /** Return true if this commondto.EntityExtractionConfig object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommondtoEntityExtractionConfig commondtoEntityExtractionConfig =
        (CommondtoEntityExtractionConfig) o;
    return Objects.equals(this.contextWindow, commondtoEntityExtractionConfig.contextWindow)
        && Objects.equals(this.enableContext, commondtoEntityExtractionConfig.enableContext)
        && Objects.equals(this.entityTypes, commondtoEntityExtractionConfig.entityTypes)
        && Objects.equals(this.fallbackMessages, commondtoEntityExtractionConfig.fallbackMessages)
        && Objects.equals(this.maxPasses, commondtoEntityExtractionConfig.maxPasses)
        && Objects.equals(this.maxTokens, commondtoEntityExtractionConfig.maxTokens)
        && Objects.equals(this.minConfidence, commondtoEntityExtractionConfig.minConfidence)
        && Objects.equals(this.model, commondtoEntityExtractionConfig.model)
        && Objects.equals(this.temperature, commondtoEntityExtractionConfig.temperature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        contextWindow,
        enableContext,
        entityTypes,
        fallbackMessages,
        maxPasses,
        maxTokens,
        minConfidence,
        model,
        temperature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommondtoEntityExtractionConfig {\n");
    sb.append("    contextWindow: ").append(toIndentedString(contextWindow)).append("\n");
    sb.append("    enableContext: ").append(toIndentedString(enableContext)).append("\n");
    sb.append("    entityTypes: ").append(toIndentedString(entityTypes)).append("\n");
    sb.append("    fallbackMessages: ").append(toIndentedString(fallbackMessages)).append("\n");
    sb.append("    maxPasses: ").append(toIndentedString(maxPasses)).append("\n");
    sb.append("    maxTokens: ").append(toIndentedString(maxTokens)).append("\n");
    sb.append("    minConfidence: ").append(toIndentedString(minConfidence)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `context_window` to the URL query string
    if (getContextWindow() != null) {
      joiner.add(
          String.format(
              java.util.Locale.ROOT,
              "%scontext_window%s=%s",
              prefix,
              suffix,
              ApiClient.urlEncode(ApiClient.valueToString(getContextWindow()))));
    }

    // add `enable_context` to the URL query string
    if (getEnableContext() != null) {
      joiner.add(
          String.format(
              java.util.Locale.ROOT,
              "%senable_context%s=%s",
              prefix,
              suffix,
              ApiClient.urlEncode(ApiClient.valueToString(getEnableContext()))));
    }

    // add `entity_types` to the URL query string
    if (getEntityTypes() != null) {
      for (int i = 0; i < getEntityTypes().size(); i++) {
        joiner.add(
            String.format(
                java.util.Locale.ROOT,
                "%sentity_types%s%s=%s",
                prefix,
                suffix,
                "".equals(suffix)
                    ? ""
                    : String.format(
                        java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
                ApiClient.urlEncode(ApiClient.valueToString(getEntityTypes().get(i)))));
      }
    }

    // add `fallback_messages` to the URL query string
    if (getFallbackMessages() != null) {
      joiner.add(
          String.format(
              java.util.Locale.ROOT,
              "%sfallback_messages%s=%s",
              prefix,
              suffix,
              ApiClient.urlEncode(ApiClient.valueToString(getFallbackMessages()))));
    }

    // add `max_passes` to the URL query string
    if (getMaxPasses() != null) {
      joiner.add(
          String.format(
              java.util.Locale.ROOT,
              "%smax_passes%s=%s",
              prefix,
              suffix,
              ApiClient.urlEncode(ApiClient.valueToString(getMaxPasses()))));
    }

    // add `max_tokens` to the URL query string
    if (getMaxTokens() != null) {
      joiner.add(
          String.format(
              java.util.Locale.ROOT,
              "%smax_tokens%s=%s",
              prefix,
              suffix,
              ApiClient.urlEncode(ApiClient.valueToString(getMaxTokens()))));
    }

    // add `min_confidence` to the URL query string
    if (getMinConfidence() != null) {
      joiner.add(
          String.format(
              java.util.Locale.ROOT,
              "%smin_confidence%s=%s",
              prefix,
              suffix,
              ApiClient.urlEncode(ApiClient.valueToString(getMinConfidence()))));
    }

    // add `model` to the URL query string
    if (getModel() != null) {
      joiner.add(
          String.format(
              java.util.Locale.ROOT,
              "%smodel%s=%s",
              prefix,
              suffix,
              ApiClient.urlEncode(ApiClient.valueToString(getModel()))));
    }

    // add `temperature` to the URL query string
    if (getTemperature() != null) {
      joiner.add(
          String.format(
              java.util.Locale.ROOT,
              "%stemperature%s=%s",
              prefix,
              suffix,
              ApiClient.urlEncode(ApiClient.valueToString(getTemperature()))));
    }

    return joiner.toString();
  }
}
