/*
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.smritea.sdk._internal.autogen.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.smritea.sdk._internal.autogen.ApiClient;
/**
 * CommondtoMemoryScope
 */
@JsonPropertyOrder({
  CommondtoMemoryScope.JSON_PROPERTY_ACTOR_ID,
  CommondtoMemoryScope.JSON_PROPERTY_ACTOR_NAME,
  CommondtoMemoryScope.JSON_PROPERTY_ACTOR_TYPE,
  CommondtoMemoryScope.JSON_PROPERTY_CONVERSATION_ID,
  CommondtoMemoryScope.JSON_PROPERTY_PARTICIPANT_IDS,
  CommondtoMemoryScope.JSON_PROPERTY_SOURCE_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class CommondtoMemoryScope {
  public static final String JSON_PROPERTY_ACTOR_ID = "actor_id";
  @javax.annotation.Nullable
  private String actorId;

  public static final String JSON_PROPERTY_ACTOR_NAME = "actor_name";
  @javax.annotation.Nullable
  private String actorName;

  /**
   * Gets or Sets actorType
   */
  public enum ActorTypeEnum {
    USER(String.valueOf("user")),
    
    AGENT(String.valueOf("agent")),
    
    SYSTEM(String.valueOf("system"));

    private String value;

    ActorTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActorTypeEnum fromValue(String value) {
      for (ActorTypeEnum b : ActorTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTOR_TYPE = "actor_type";
  @javax.annotation.Nullable
  private ActorTypeEnum actorType;

  public static final String JSON_PROPERTY_CONVERSATION_ID = "conversation_id";
  @javax.annotation.Nullable
  private String conversationId;

  public static final String JSON_PROPERTY_PARTICIPANT_IDS = "participant_ids";
  @javax.annotation.Nullable
  private List<String> participantIds = new ArrayList<>();

  /**
   * Gets or Sets sourceType
   */
  public enum SourceTypeEnum {
    CONVERSATION(String.valueOf("conversation")),
    
    DOCUMENT(String.valueOf("document")),
    
    API(String.valueOf("api"));

    private String value;

    SourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceTypeEnum fromValue(String value) {
      for (SourceTypeEnum b : SourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SOURCE_TYPE = "source_type";
  @javax.annotation.Nullable
  private SourceTypeEnum sourceType;

  public CommondtoMemoryScope() { 
  }

  public CommondtoMemoryScope actorId(@javax.annotation.Nullable String actorId) {
    this.actorId = actorId;
    return this;
  }

  /**
   * Get actorId
   * @return actorId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTOR_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getActorId() {
    return actorId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTOR_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActorId(@javax.annotation.Nullable String actorId) {
    this.actorId = actorId;
  }


  public CommondtoMemoryScope actorName(@javax.annotation.Nullable String actorName) {
    this.actorName = actorName;
    return this;
  }

  /**
   * Get actorName
   * @return actorName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTOR_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getActorName() {
    return actorName;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTOR_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActorName(@javax.annotation.Nullable String actorName) {
    this.actorName = actorName;
  }


  public CommondtoMemoryScope actorType(@javax.annotation.Nullable ActorTypeEnum actorType) {
    this.actorType = actorType;
    return this;
  }

  /**
   * Get actorType
   * @return actorType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTOR_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ActorTypeEnum getActorType() {
    return actorType;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTOR_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActorType(@javax.annotation.Nullable ActorTypeEnum actorType) {
    this.actorType = actorType;
  }


  public CommondtoMemoryScope conversationId(@javax.annotation.Nullable String conversationId) {
    this.conversationId = conversationId;
    return this;
  }

  /**
   * Get conversationId
   * @return conversationId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONVERSATION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getConversationId() {
    return conversationId;
  }


  @JsonProperty(value = JSON_PROPERTY_CONVERSATION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConversationId(@javax.annotation.Nullable String conversationId) {
    this.conversationId = conversationId;
  }


  public CommondtoMemoryScope participantIds(@javax.annotation.Nullable List<String> participantIds) {
    this.participantIds = participantIds;
    return this;
  }

  public CommondtoMemoryScope addParticipantIdsItem(String participantIdsItem) {
    if (this.participantIds == null) {
      this.participantIds = new ArrayList<>();
    }
    this.participantIds.add(participantIdsItem);
    return this;
  }

  /**
   * ParticipantIDs lists actor IDs whose shared conversations to search. The search service expands this to all conversations where ALL listed actors participated (AND semantics — conversations missing even one actor are excluded). Mutually exclusive with ConversationID; if both are set, ConversationID takes precedence. Minimum 2 IDs required.
   * @return participantIds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARTICIPANT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getParticipantIds() {
    return participantIds;
  }


  @JsonProperty(value = JSON_PROPERTY_PARTICIPANT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParticipantIds(@javax.annotation.Nullable List<String> participantIds) {
    this.participantIds = participantIds;
  }


  public CommondtoMemoryScope sourceType(@javax.annotation.Nullable SourceTypeEnum sourceType) {
    this.sourceType = sourceType;
    return this;
  }

  /**
   * Get sourceType
   * @return sourceType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SourceTypeEnum getSourceType() {
    return sourceType;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceType(@javax.annotation.Nullable SourceTypeEnum sourceType) {
    this.sourceType = sourceType;
  }


  /**
   * Return true if this commondto.MemoryScope object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommondtoMemoryScope commondtoMemoryScope = (CommondtoMemoryScope) o;
    return Objects.equals(this.actorId, commondtoMemoryScope.actorId) &&
        Objects.equals(this.actorName, commondtoMemoryScope.actorName) &&
        Objects.equals(this.actorType, commondtoMemoryScope.actorType) &&
        Objects.equals(this.conversationId, commondtoMemoryScope.conversationId) &&
        Objects.equals(this.participantIds, commondtoMemoryScope.participantIds) &&
        Objects.equals(this.sourceType, commondtoMemoryScope.sourceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actorId, actorName, actorType, conversationId, participantIds, sourceType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommondtoMemoryScope {\n");
    sb.append("    actorId: ").append(toIndentedString(actorId)).append("\n");
    sb.append("    actorName: ").append(toIndentedString(actorName)).append("\n");
    sb.append("    actorType: ").append(toIndentedString(actorType)).append("\n");
    sb.append("    conversationId: ").append(toIndentedString(conversationId)).append("\n");
    sb.append("    participantIds: ").append(toIndentedString(participantIds)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `actor_id` to the URL query string
    if (getActorId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sactor_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActorId()))));
    }

    // add `actor_name` to the URL query string
    if (getActorName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sactor_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActorName()))));
    }

    // add `actor_type` to the URL query string
    if (getActorType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sactor_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActorType()))));
    }

    // add `conversation_id` to the URL query string
    if (getConversationId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sconversation_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConversationId()))));
    }

    // add `participant_ids` to the URL query string
    if (getParticipantIds() != null) {
      for (int i = 0; i < getParticipantIds().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sparticipant_ids%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getParticipantIds().get(i)))));
      }
    }

    // add `source_type` to the URL query string
    if (getSourceType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssource_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSourceType()))));
    }

    return joiner.toString();
  }
}

