/*
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.smritea.sdk._internal.autogen.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.smritea.sdk._internal.autogen.model.CommondtoMemoryScope;
import ai.smritea.sdk._internal.autogen.model.CommondtoRelativeStandingConfig;
import ai.smritea.sdk._internal.autogen.model.ExplainTrace;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.smritea.sdk._internal.autogen.ApiClient;
/**
 * MemoryCreateMemoryResponse
 */
@JsonPropertyOrder({
  MemoryCreateMemoryResponse.JSON_PROPERTY_ACTIVE_FROM,
  MemoryCreateMemoryResponse.JSON_PROPERTY_ACTIVE_TO,
  MemoryCreateMemoryResponse.JSON_PROPERTY_APP_ID,
  MemoryCreateMemoryResponse.JSON_PROPERTY_CONTENT,
  MemoryCreateMemoryResponse.JSON_PROPERTY_CREATED_AT,
  MemoryCreateMemoryResponse.JSON_PROPERTY_EXPLAIN_TRACE,
  MemoryCreateMemoryResponse.JSON_PROPERTY_ID,
  MemoryCreateMemoryResponse.JSON_PROPERTY_METADATA,
  MemoryCreateMemoryResponse.JSON_PROPERTY_RELATIVE_STANDING,
  MemoryCreateMemoryResponse.JSON_PROPERTY_SCOPE,
  MemoryCreateMemoryResponse.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class MemoryCreateMemoryResponse {
  public static final String JSON_PROPERTY_ACTIVE_FROM = "active_from";
  @javax.annotation.Nullable
  private String activeFrom;

  public static final String JSON_PROPERTY_ACTIVE_TO = "active_to";
  @javax.annotation.Nullable
  private String activeTo;

  public static final String JSON_PROPERTY_APP_ID = "app_id";
  @javax.annotation.Nullable
  private String appId;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nullable
  private String content;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private String createdAt;

  public static final String JSON_PROPERTY_EXPLAIN_TRACE = "explain_trace";
  @javax.annotation.Nullable
  private ExplainTrace explainTrace;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Object metadata;

  public static final String JSON_PROPERTY_RELATIVE_STANDING = "relative_standing";
  @javax.annotation.Nullable
  private CommondtoRelativeStandingConfig relativeStanding;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @javax.annotation.Nullable
  private CommondtoMemoryScope scope;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @javax.annotation.Nullable
  private String updatedAt;

  public MemoryCreateMemoryResponse() { 
  }

  public MemoryCreateMemoryResponse activeFrom(@javax.annotation.Nullable String activeFrom) {
    this.activeFrom = activeFrom;
    return this;
  }

  /**
   * Get activeFrom
   * @return activeFrom
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVE_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getActiveFrom() {
    return activeFrom;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVE_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActiveFrom(@javax.annotation.Nullable String activeFrom) {
    this.activeFrom = activeFrom;
  }


  public MemoryCreateMemoryResponse activeTo(@javax.annotation.Nullable String activeTo) {
    this.activeTo = activeTo;
    return this;
  }

  /**
   * Get activeTo
   * @return activeTo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVE_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getActiveTo() {
    return activeTo;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVE_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActiveTo(@javax.annotation.Nullable String activeTo) {
    this.activeTo = activeTo;
  }


  public MemoryCreateMemoryResponse appId(@javax.annotation.Nullable String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * Get appId
   * @return appId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAppId() {
    return appId;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppId(@javax.annotation.Nullable String appId) {
    this.appId = appId;
  }


  public MemoryCreateMemoryResponse content(@javax.annotation.Nullable String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(@javax.annotation.Nullable String content) {
    this.content = content;
  }


  public MemoryCreateMemoryResponse createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public MemoryCreateMemoryResponse explainTrace(@javax.annotation.Nullable ExplainTrace explainTrace) {
    this.explainTrace = explainTrace;
    return this;
  }

  /**
   * Get explainTrace
   * @return explainTrace
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPLAIN_TRACE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ExplainTrace getExplainTrace() {
    return explainTrace;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPLAIN_TRACE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExplainTrace(@javax.annotation.Nullable ExplainTrace explainTrace) {
    this.explainTrace = explainTrace;
  }


  public MemoryCreateMemoryResponse id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public MemoryCreateMemoryResponse metadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }


  public MemoryCreateMemoryResponse relativeStanding(@javax.annotation.Nullable CommondtoRelativeStandingConfig relativeStanding) {
    this.relativeStanding = relativeStanding;
    return this;
  }

  /**
   * Get relativeStanding
   * @return relativeStanding
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RELATIVE_STANDING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CommondtoRelativeStandingConfig getRelativeStanding() {
    return relativeStanding;
  }


  @JsonProperty(value = JSON_PROPERTY_RELATIVE_STANDING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelativeStanding(@javax.annotation.Nullable CommondtoRelativeStandingConfig relativeStanding) {
    this.relativeStanding = relativeStanding;
  }


  public MemoryCreateMemoryResponse scope(@javax.annotation.Nullable CommondtoMemoryScope scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Scope contains the memory&#39;s actor, conversation, and source context.
   * @return scope
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CommondtoMemoryScope getScope() {
    return scope;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@javax.annotation.Nullable CommondtoMemoryScope scope) {
    this.scope = scope;
  }


  public MemoryCreateMemoryResponse updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this memory.CreateMemoryResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemoryCreateMemoryResponse memoryCreateMemoryResponse = (MemoryCreateMemoryResponse) o;
    return Objects.equals(this.activeFrom, memoryCreateMemoryResponse.activeFrom) &&
        Objects.equals(this.activeTo, memoryCreateMemoryResponse.activeTo) &&
        Objects.equals(this.appId, memoryCreateMemoryResponse.appId) &&
        Objects.equals(this.content, memoryCreateMemoryResponse.content) &&
        Objects.equals(this.createdAt, memoryCreateMemoryResponse.createdAt) &&
        Objects.equals(this.explainTrace, memoryCreateMemoryResponse.explainTrace) &&
        Objects.equals(this.id, memoryCreateMemoryResponse.id) &&
        Objects.equals(this.metadata, memoryCreateMemoryResponse.metadata) &&
        Objects.equals(this.relativeStanding, memoryCreateMemoryResponse.relativeStanding) &&
        Objects.equals(this.scope, memoryCreateMemoryResponse.scope) &&
        Objects.equals(this.updatedAt, memoryCreateMemoryResponse.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeFrom, activeTo, appId, content, createdAt, explainTrace, id, metadata, relativeStanding, scope, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemoryCreateMemoryResponse {\n");
    sb.append("    activeFrom: ").append(toIndentedString(activeFrom)).append("\n");
    sb.append("    activeTo: ").append(toIndentedString(activeTo)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    explainTrace: ").append(toIndentedString(explainTrace)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    relativeStanding: ").append(toIndentedString(relativeStanding)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `active_from` to the URL query string
    if (getActiveFrom() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sactive_from%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActiveFrom()))));
    }

    // add `active_to` to the URL query string
    if (getActiveTo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sactive_to%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActiveTo()))));
    }

    // add `app_id` to the URL query string
    if (getAppId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sapp_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAppId()))));
    }

    // add `content` to the URL query string
    if (getContent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContent()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `explain_trace` to the URL query string
    if (getExplainTrace() != null) {
      joiner.add(getExplainTrace().toUrlQueryString(prefix + "explain_trace" + suffix));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smetadata%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetadata()))));
    }

    // add `relative_standing` to the URL query string
    if (getRelativeStanding() != null) {
      joiner.add(getRelativeStanding().toUrlQueryString(prefix + "relative_standing" + suffix));
    }

    // add `scope` to the URL query string
    if (getScope() != null) {
      joiner.add(getScope().toUrlQueryString(prefix + "scope" + suffix));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    return joiner.toString();
  }
}

