/*
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.smritea.sdk._internal.autogen.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.smritea.sdk._internal.autogen.model.MemoryScope;
import ai.smritea.sdk._internal.autogen.model.RerankerType;
import ai.smritea.sdk._internal.autogen.model.SearchMethod;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.smritea.sdk._internal.autogen.ApiClient;
/**
 * SearchMemoryRequest
 */
@JsonPropertyOrder({
  SearchMemoryRequest.JSON_PROPERTY_APP_ID,
  SearchMemoryRequest.JSON_PROPERTY_FROM_TIME,
  SearchMemoryRequest.JSON_PROPERTY_GRAPH_DEPTH,
  SearchMemoryRequest.JSON_PROPERTY_LIMIT,
  SearchMemoryRequest.JSON_PROPERTY_METADATA_FILTER,
  SearchMemoryRequest.JSON_PROPERTY_METHOD,
  SearchMemoryRequest.JSON_PROPERTY_QUERY,
  SearchMemoryRequest.JSON_PROPERTY_RERANKER_TYPE,
  SearchMemoryRequest.JSON_PROPERTY_SCOPE,
  SearchMemoryRequest.JSON_PROPERTY_THRESHOLD,
  SearchMemoryRequest.JSON_PROPERTY_TO_TIME,
  SearchMemoryRequest.JSON_PROPERTY_VALID_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class SearchMemoryRequest {
  public static final String JSON_PROPERTY_APP_ID = "app_id";
  @javax.annotation.Nonnull
  private String appId;

  public static final String JSON_PROPERTY_FROM_TIME = "from_time";
  @javax.annotation.Nullable
  private String fromTime;

  public static final String JSON_PROPERTY_GRAPH_DEPTH = "graph_depth";
  @javax.annotation.Nullable
  private Integer graphDepth;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nullable
  private Integer limit;

  public static final String JSON_PROPERTY_METADATA_FILTER = "metadata_filter";
  @javax.annotation.Nullable
  private Object metadataFilter;

  public static final String JSON_PROPERTY_METHOD = "method";
  @javax.annotation.Nullable
  private SearchMethod method;

  public static final String JSON_PROPERTY_QUERY = "query";
  @javax.annotation.Nonnull
  private String query;

  public static final String JSON_PROPERTY_RERANKER_TYPE = "reranker_type";
  @javax.annotation.Nullable
  private RerankerType rerankerType;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @javax.annotation.Nullable
  private MemoryScope scope;

  public static final String JSON_PROPERTY_THRESHOLD = "threshold";
  @javax.annotation.Nullable
  private BigDecimal threshold;

  public static final String JSON_PROPERTY_TO_TIME = "to_time";
  @javax.annotation.Nullable
  private String toTime;

  public static final String JSON_PROPERTY_VALID_AT = "valid_at";
  @javax.annotation.Nullable
  private String validAt;

  public SearchMemoryRequest() { 
  }

  public SearchMemoryRequest appId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * Get appId
   * @return appId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_APP_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAppId() {
    return appId;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
  }


  public SearchMemoryRequest fromTime(@javax.annotation.Nullable String fromTime) {
    this.fromTime = fromTime;
    return this;
  }

  /**
   * FromTime filters memories that overlap with time range [FromTime, ToTime] (ISO 8601 format). Must be used together with ToTime.
   * @return fromTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFromTime() {
    return fromTime;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromTime(@javax.annotation.Nullable String fromTime) {
    this.fromTime = fromTime;
  }


  public SearchMemoryRequest graphDepth(@javax.annotation.Nullable Integer graphDepth) {
    this.graphDepth = graphDepth;
    return this;
  }

  /**
   * 0&#x3D;use app config, 1-5&#x3D;override traversal depth
   * maximum: 5
   * @return graphDepth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRAPH_DEPTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getGraphDepth() {
    return graphDepth;
  }


  @JsonProperty(value = JSON_PROPERTY_GRAPH_DEPTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGraphDepth(@javax.annotation.Nullable Integer graphDepth) {
    this.graphDepth = graphDepth;
  }


  public SearchMemoryRequest limit(@javax.annotation.Nullable Integer limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Get limit
   * maximum: 100
   * @return limit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimit(@javax.annotation.Nullable Integer limit) {
    this.limit = limit;
  }


  public SearchMemoryRequest metadataFilter(@javax.annotation.Nullable Object metadataFilter) {
    this.metadataFilter = metadataFilter;
    return this;
  }

  /**
   * MetadataFilter filters memories by user-provided key-value metadata. Only memories whose metadata contains ALL specified key-value pairs are returned.
   * @return metadataFilter
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getMetadataFilter() {
    return metadataFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadataFilter(@javax.annotation.Nullable Object metadataFilter) {
    this.metadataFilter = metadataFilter;
  }


  public SearchMemoryRequest method(@javax.annotation.Nullable SearchMethod method) {
    this.method = method;
    return this;
  }

  /**
   * Get method
   * @return method
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SearchMethod getMethod() {
    return method;
  }


  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethod(@javax.annotation.Nullable SearchMethod method) {
    this.method = method;
  }


  public SearchMemoryRequest query(@javax.annotation.Nonnull String query) {
    this.query = query;
    return this;
  }

  /**
   * Get query
   * @return query
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUERY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getQuery() {
    return query;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuery(@javax.annotation.Nonnull String query) {
    this.query = query;
  }


  public SearchMemoryRequest rerankerType(@javax.annotation.Nullable RerankerType rerankerType) {
    this.rerankerType = rerankerType;
    return this;
  }

  /**
   * RerankerType overrides the reranker for this request (optional). If nil, uses app config reranker. Only applies to deep_search method.
   * @return rerankerType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RERANKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RerankerType getRerankerType() {
    return rerankerType;
  }


  @JsonProperty(value = JSON_PROPERTY_RERANKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRerankerType(@javax.annotation.Nullable RerankerType rerankerType) {
    this.rerankerType = rerankerType;
  }


  public SearchMemoryRequest scope(@javax.annotation.Nullable MemoryScope scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Scope groups actor, conversation, and source filtering fields. Zero-value fields mean \&quot;no filter\&quot; (searches across all).
   * @return scope
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MemoryScope getScope() {
    return scope;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@javax.annotation.Nullable MemoryScope scope) {
    this.scope = scope;
  }


  public SearchMemoryRequest threshold(@javax.annotation.Nullable BigDecimal threshold) {
    this.threshold = threshold;
    return this;
  }

  /**
   * 0&#x3D;no filtering (pipeline uses RRF scores, not cosine similarity)
   * minimum: 0
   * maximum: 1
   * @return threshold
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THRESHOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getThreshold() {
    return threshold;
  }


  @JsonProperty(value = JSON_PROPERTY_THRESHOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThreshold(@javax.annotation.Nullable BigDecimal threshold) {
    this.threshold = threshold;
  }


  public SearchMemoryRequest toTime(@javax.annotation.Nullable String toTime) {
    this.toTime = toTime;
    return this;
  }

  /**
   * ToTime is the end of the time range filter (ISO 8601 format). Must be used together with FromTime.
   * @return toTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getToTime() {
    return toTime;
  }


  @JsonProperty(value = JSON_PROPERTY_TO_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToTime(@javax.annotation.Nullable String toTime) {
    this.toTime = toTime;
  }


  public SearchMemoryRequest validAt(@javax.annotation.Nullable String validAt) {
    this.validAt = validAt;
    return this;
  }

  /**
   * ValidAt filters memories valid at a specific point in time (ISO 8601 format). A memory is valid if: active_from &lt;&#x3D; ValidAt AND (active_to is null OR active_to &gt;&#x3D; ValidAt) Mutually exclusive with FromTime/ToTime.
   * @return validAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALID_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getValidAt() {
    return validAt;
  }


  @JsonProperty(value = JSON_PROPERTY_VALID_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidAt(@javax.annotation.Nullable String validAt) {
    this.validAt = validAt;
  }


  /**
   * Return true if this SearchMemoryRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchMemoryRequest searchMemoryRequest = (SearchMemoryRequest) o;
    return Objects.equals(this.appId, searchMemoryRequest.appId) &&
        Objects.equals(this.fromTime, searchMemoryRequest.fromTime) &&
        Objects.equals(this.graphDepth, searchMemoryRequest.graphDepth) &&
        Objects.equals(this.limit, searchMemoryRequest.limit) &&
        Objects.equals(this.metadataFilter, searchMemoryRequest.metadataFilter) &&
        Objects.equals(this.method, searchMemoryRequest.method) &&
        Objects.equals(this.query, searchMemoryRequest.query) &&
        Objects.equals(this.rerankerType, searchMemoryRequest.rerankerType) &&
        Objects.equals(this.scope, searchMemoryRequest.scope) &&
        Objects.equals(this.threshold, searchMemoryRequest.threshold) &&
        Objects.equals(this.toTime, searchMemoryRequest.toTime) &&
        Objects.equals(this.validAt, searchMemoryRequest.validAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, fromTime, graphDepth, limit, metadataFilter, method, query, rerankerType, scope, threshold, toTime, validAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchMemoryRequest {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    fromTime: ").append(toIndentedString(fromTime)).append("\n");
    sb.append("    graphDepth: ").append(toIndentedString(graphDepth)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    metadataFilter: ").append(toIndentedString(metadataFilter)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    rerankerType: ").append(toIndentedString(rerankerType)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    toTime: ").append(toIndentedString(toTime)).append("\n");
    sb.append("    validAt: ").append(toIndentedString(validAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `app_id` to the URL query string
    if (getAppId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sapp_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAppId()))));
    }

    // add `from_time` to the URL query string
    if (getFromTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfrom_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFromTime()))));
    }

    // add `graph_depth` to the URL query string
    if (getGraphDepth() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgraph_depth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGraphDepth()))));
    }

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slimit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLimit()))));
    }

    // add `metadata_filter` to the URL query string
    if (getMetadataFilter() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smetadata_filter%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetadataFilter()))));
    }

    // add `method` to the URL query string
    if (getMethod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMethod()))));
    }

    // add `query` to the URL query string
    if (getQuery() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squery%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuery()))));
    }

    // add `reranker_type` to the URL query string
    if (getRerankerType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreranker_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRerankerType()))));
    }

    // add `scope` to the URL query string
    if (getScope() != null) {
      joiner.add(getScope().toUrlQueryString(prefix + "scope" + suffix));
    }

    // add `threshold` to the URL query string
    if (getThreshold() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthreshold%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThreshold()))));
    }

    // add `to_time` to the URL query string
    if (getToTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sto_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToTime()))));
    }

    // add `valid_at` to the URL query string
    if (getValidAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalid_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValidAt()))));
    }

    return joiner.toString();
  }
}

