/*
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.smritea.sdk._internal.autogen.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.smritea.sdk._internal.autogen.model.MemoryScope;
import ai.smritea.sdk._internal.autogen.model.RerankerType;
import ai.smritea.sdk._internal.autogen.model.SearchMethod;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.smritea.sdk._internal.autogen.ApiClient;
/**
 * SearchMemoryRequest
 */
@JsonPropertyOrder({
  SearchMemoryRequest.JSON_PROPERTY_APP_ID,
  SearchMemoryRequest.JSON_PROPERTY_FROM_TIME,
  SearchMemoryRequest.JSON_PROPERTY_GRAPH_DEPTH,
  SearchMemoryRequest.JSON_PROPERTY_LIMIT,
  SearchMemoryRequest.JSON_PROPERTY_METADATA_FILTER,
  SearchMemoryRequest.JSON_PROPERTY_METHOD,
  SearchMemoryRequest.JSON_PROPERTY_QUERY,
  SearchMemoryRequest.JSON_PROPERTY_RERANKER_TYPE,
  SearchMemoryRequest.JSON_PROPERTY_SCOPE,
  SearchMemoryRequest.JSON_PROPERTY_SPEAKER_ACTOR_ID,
  SearchMemoryRequest.JSON_PROPERTY_TO_TIME,
  SearchMemoryRequest.JSON_PROPERTY_VALID_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class SearchMemoryRequest {
  public static final String JSON_PROPERTY_APP_ID = "app_id";
  @javax.annotation.Nonnull
  private String appId;

  public static final String JSON_PROPERTY_FROM_TIME = "from_time";
  @javax.annotation.Nullable
  private String fromTime;

  public static final String JSON_PROPERTY_GRAPH_DEPTH = "graph_depth";
  @javax.annotation.Nullable
  private Integer graphDepth;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nullable
  private Integer limit;

  public static final String JSON_PROPERTY_METADATA_FILTER = "metadata_filter";
  @javax.annotation.Nullable
  private Object metadataFilter;

  public static final String JSON_PROPERTY_METHOD = "method";
  @javax.annotation.Nullable
  private SearchMethod method;

  public static final String JSON_PROPERTY_QUERY = "query";
  @javax.annotation.Nonnull
  private String query;

  public static final String JSON_PROPERTY_RERANKER_TYPE = "reranker_type";
  @javax.annotation.Nullable
  private RerankerType rerankerType;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @javax.annotation.Nullable
  private MemoryScope scope;

  public static final String JSON_PROPERTY_SPEAKER_ACTOR_ID = "speaker_actor_id";
  @javax.annotation.Nullable
  private String speakerActorId;

  public static final String JSON_PROPERTY_TO_TIME = "to_time";
  @javax.annotation.Nullable
  private String toTime;

  public static final String JSON_PROPERTY_VALID_AT = "valid_at";
  @javax.annotation.Nullable
  private String validAt;

  public SearchMemoryRequest() { 
  }

  public SearchMemoryRequest appId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * Get appId
   * @return appId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_APP_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAppId() {
    return appId;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
  }


  public SearchMemoryRequest fromTime(@javax.annotation.Nullable String fromTime) {
    this.fromTime = fromTime;
    return this;
  }

  /**
   * FromTime is the start of a time-range filter, RFC 3339. Returns memories whose validity period overlaps [from_time, ∞): memories still valid at from_time or valid after it. Can be used alone (open-ended). With to_time the range is [from_time, to_time]. Cannot be combined with valid_at.
   * @return fromTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFromTime() {
    return fromTime;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromTime(@javax.annotation.Nullable String fromTime) {
    this.fromTime = fromTime;
  }


  public SearchMemoryRequest graphDepth(@javax.annotation.Nullable Integer graphDepth) {
    this.graphDepth = graphDepth;
    return this;
  }

  /**
   * 0 &#x3D; system graph_max_hops; 1..services.search.graph_max_hops_max
   * minimum: 0
   * @return graphDepth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRAPH_DEPTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getGraphDepth() {
    return graphDepth;
  }


  @JsonProperty(value = JSON_PROPERTY_GRAPH_DEPTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGraphDepth(@javax.annotation.Nullable Integer graphDepth) {
    this.graphDepth = graphDepth;
  }


  public SearchMemoryRequest limit(@javax.annotation.Nullable Integer limit) {
    this.limit = limit;
    return this;
  }

  /**
   * 0 &#x3D; app top_n; must be &lt;&#x3D; services.search.top_n_max (checked in the service layer).
   * @return limit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimit(@javax.annotation.Nullable Integer limit) {
    this.limit = limit;
  }


  public SearchMemoryRequest metadataFilter(@javax.annotation.Nullable Object metadataFilter) {
    this.metadataFilter = metadataFilter;
    return this;
  }

  /**
   * MetadataFilter filters memories by user-provided key-value metadata. Only memories whose metadata contains ALL specified key-value pairs are returned.
   * @return metadataFilter
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getMetadataFilter() {
    return metadataFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadataFilter(@javax.annotation.Nullable Object metadataFilter) {
    this.metadataFilter = metadataFilter;
  }


  public SearchMemoryRequest method(@javax.annotation.Nullable SearchMethod method) {
    this.method = method;
    return this;
  }

  /**
   * Get method
   * @return method
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SearchMethod getMethod() {
    return method;
  }


  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethod(@javax.annotation.Nullable SearchMethod method) {
    this.method = method;
  }


  public SearchMemoryRequest query(@javax.annotation.Nonnull String query) {
    this.query = query;
    return this;
  }

  /**
   * Get query
   * @return query
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUERY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getQuery() {
    return query;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuery(@javax.annotation.Nonnull String query) {
    this.query = query;
  }


  public SearchMemoryRequest rerankerType(@javax.annotation.Nullable RerankerType rerankerType) {
    this.rerankerType = rerankerType;
    return this;
  }

  /**
   * RerankerType overrides the reranker for this request (optional). If nil, uses app config reranker. Only applies to deep_search method.
   * @return rerankerType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RERANKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RerankerType getRerankerType() {
    return rerankerType;
  }


  @JsonProperty(value = JSON_PROPERTY_RERANKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRerankerType(@javax.annotation.Nullable RerankerType rerankerType) {
    this.rerankerType = rerankerType;
  }


  public SearchMemoryRequest scope(@javax.annotation.Nullable MemoryScope scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Scope groups actor, conversation, and source filtering fields. Zero-value fields mean \&quot;no filter\&quot; (searches across all).
   * @return scope
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MemoryScope getScope() {
    return scope;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@javax.annotation.Nullable MemoryScope scope) {
    this.scope = scope;
  }


  public SearchMemoryRequest speakerActorId(@javax.annotation.Nullable String speakerActorId) {
    this.speakerActorId = speakerActorId;
    return this;
  }

  /**
   * SpeakerActorID identifies which actor is making this search request. It is NEVER used for filtering — it does not narrow, exclude, or bias which memories are returned. It exists purely for identification: audit logging, telemetry, and any future personalization/access-control hook that needs to know \&quot;who is asking\&quot; independent of \&quot;which memories to include.\&quot; That second concern (result filtering) is entirely owned by Scope below. Deliberately top-level, not nested inside Scope, so it can never be confused with — or accidentally coupled to — the filter fields. Optional: omit if the caller has no meaningful requester identity (e.g. an anonymous or system-initiated search).
   * @return speakerActorId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPEAKER_ACTOR_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSpeakerActorId() {
    return speakerActorId;
  }


  @JsonProperty(value = JSON_PROPERTY_SPEAKER_ACTOR_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpeakerActorId(@javax.annotation.Nullable String speakerActorId) {
    this.speakerActorId = speakerActorId;
  }


  public SearchMemoryRequest toTime(@javax.annotation.Nullable String toTime) {
    this.toTime = toTime;
    return this;
  }

  /**
   * ToTime is the end of a time-range filter, RFC 3339 (inclusive). Returns memories whose validity period overlaps (−∞, to_time]: memories that started on or before to_time. Can be used alone (open-ended). With from_time the range is [from_time, to_time] and from_time must be on or before to_time. Cannot be combined with valid_at.
   * @return toTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getToTime() {
    return toTime;
  }


  @JsonProperty(value = JSON_PROPERTY_TO_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToTime(@javax.annotation.Nullable String toTime) {
    this.toTime = toTime;
  }


  public SearchMemoryRequest validAt(@javax.annotation.Nullable String validAt) {
    this.validAt = validAt;
    return this;
  }

  /**
   * ValidAt returns memories valid at exactly this moment (active_from &lt;&#x3D; valid_at and active_to empty or &gt;&#x3D; valid_at), RFC 3339. Mutually exclusive with from_time and to_time.
   * @return validAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALID_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getValidAt() {
    return validAt;
  }


  @JsonProperty(value = JSON_PROPERTY_VALID_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidAt(@javax.annotation.Nullable String validAt) {
    this.validAt = validAt;
  }


  /**
   * Return true if this SearchMemoryRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchMemoryRequest searchMemoryRequest = (SearchMemoryRequest) o;
    return Objects.equals(this.appId, searchMemoryRequest.appId) &&
        Objects.equals(this.fromTime, searchMemoryRequest.fromTime) &&
        Objects.equals(this.graphDepth, searchMemoryRequest.graphDepth) &&
        Objects.equals(this.limit, searchMemoryRequest.limit) &&
        Objects.equals(this.metadataFilter, searchMemoryRequest.metadataFilter) &&
        Objects.equals(this.method, searchMemoryRequest.method) &&
        Objects.equals(this.query, searchMemoryRequest.query) &&
        Objects.equals(this.rerankerType, searchMemoryRequest.rerankerType) &&
        Objects.equals(this.scope, searchMemoryRequest.scope) &&
        Objects.equals(this.speakerActorId, searchMemoryRequest.speakerActorId) &&
        Objects.equals(this.toTime, searchMemoryRequest.toTime) &&
        Objects.equals(this.validAt, searchMemoryRequest.validAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, fromTime, graphDepth, limit, metadataFilter, method, query, rerankerType, scope, speakerActorId, toTime, validAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchMemoryRequest {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    fromTime: ").append(toIndentedString(fromTime)).append("\n");
    sb.append("    graphDepth: ").append(toIndentedString(graphDepth)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    metadataFilter: ").append(toIndentedString(metadataFilter)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    rerankerType: ").append(toIndentedString(rerankerType)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    speakerActorId: ").append(toIndentedString(speakerActorId)).append("\n");
    sb.append("    toTime: ").append(toIndentedString(toTime)).append("\n");
    sb.append("    validAt: ").append(toIndentedString(validAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `app_id` to the URL query string
    if (getAppId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sapp_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAppId()))));
    }

    // add `from_time` to the URL query string
    if (getFromTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfrom_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFromTime()))));
    }

    // add `graph_depth` to the URL query string
    if (getGraphDepth() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgraph_depth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGraphDepth()))));
    }

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slimit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLimit()))));
    }

    // add `metadata_filter` to the URL query string
    if (getMetadataFilter() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smetadata_filter%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetadataFilter()))));
    }

    // add `method` to the URL query string
    if (getMethod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMethod()))));
    }

    // add `query` to the URL query string
    if (getQuery() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squery%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuery()))));
    }

    // add `reranker_type` to the URL query string
    if (getRerankerType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreranker_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRerankerType()))));
    }

    // add `scope` to the URL query string
    if (getScope() != null) {
      joiner.add(getScope().toUrlQueryString(prefix + "scope" + suffix));
    }

    // add `speaker_actor_id` to the URL query string
    if (getSpeakerActorId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sspeaker_actor_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSpeakerActorId()))));
    }

    // add `to_time` to the URL query string
    if (getToTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sto_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToTime()))));
    }

    // add `valid_at` to the URL query string
    if (getValidAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalid_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValidAt()))));
    }

    return joiner.toString();
  }
}

