/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommondtoAPIError
 */
export interface CommondtoAPIError {
    /**
     * Code is a machine-readable error code (e.g., "validation_error", "not_found").
     * @type {string}
     * @memberof CommondtoAPIError
     */
    code?: string;
    /**
     * Message is a human-readable description of what went wrong.
     * @type {string}
     * @memberof CommondtoAPIError
     */
    message?: string;
}

/**
 * Check if a given object implements the CommondtoAPIError interface.
 */
export function instanceOfCommondtoAPIError(value: object): value is CommondtoAPIError {
    return true;
}

export function CommondtoAPIErrorFromJSON(json: any): CommondtoAPIError {
    return CommondtoAPIErrorFromJSONTyped(json, false);
}

export function CommondtoAPIErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommondtoAPIError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CommondtoAPIErrorToJSON(json: any): CommondtoAPIError {
    return CommondtoAPIErrorToJSONTyped(json, false);
}

export function CommondtoAPIErrorToJSONTyped(value?: CommondtoAPIError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

