/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommondtoMemoryScope
 */
export interface CommondtoMemoryScope {
    /**
     * 
     * @type {string}
     * @memberof CommondtoMemoryScope
     */
    actorId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommondtoMemoryScope
     */
    actorName?: string;
    /**
     * 
     * @type {CommondtoMemoryScopeActorTypeEnum}
     * @memberof CommondtoMemoryScope
     */
    actorType?: CommondtoMemoryScopeActorTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CommondtoMemoryScope
     */
    conversationId?: string;
    /**
     * ParticipantIDs lists actor IDs whose shared conversations to search. The search service
     * expands this to all conversations where ALL listed actors participated (AND semantics —
     * conversations missing even one actor are excluded). Mutually exclusive with ConversationID;
     * if both are set, ConversationID takes precedence. Minimum 2 IDs required.
     * @type {Array<string>}
     * @memberof CommondtoMemoryScope
     */
    participantIds?: Array<string>;
    /**
     * 
     * @type {CommondtoMemoryScopeSourceTypeEnum}
     * @memberof CommondtoMemoryScope
     */
    sourceType?: CommondtoMemoryScopeSourceTypeEnum;
}


/**
 * @export
 */
export const CommondtoMemoryScopeActorTypeEnum = {
    User: 'user',
    Agent: 'agent',
    System: 'system'
} as const;
export type CommondtoMemoryScopeActorTypeEnum = typeof CommondtoMemoryScopeActorTypeEnum[keyof typeof CommondtoMemoryScopeActorTypeEnum];

/**
 * @export
 */
export const CommondtoMemoryScopeSourceTypeEnum = {
    Conversation: 'conversation',
    Document: 'document',
    Api: 'api'
} as const;
export type CommondtoMemoryScopeSourceTypeEnum = typeof CommondtoMemoryScopeSourceTypeEnum[keyof typeof CommondtoMemoryScopeSourceTypeEnum];


/**
 * Check if a given object implements the CommondtoMemoryScope interface.
 */
export function instanceOfCommondtoMemoryScope(value: object): value is CommondtoMemoryScope {
    return true;
}

export function CommondtoMemoryScopeFromJSON(json: any): CommondtoMemoryScope {
    return CommondtoMemoryScopeFromJSONTyped(json, false);
}

export function CommondtoMemoryScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommondtoMemoryScope {
    if (json == null) {
        return json;
    }
    return {
        
        'actorId': json['actor_id'] == null ? undefined : json['actor_id'],
        'actorName': json['actor_name'] == null ? undefined : json['actor_name'],
        'actorType': json['actor_type'] == null ? undefined : json['actor_type'],
        'conversationId': json['conversation_id'] == null ? undefined : json['conversation_id'],
        'participantIds': json['participant_ids'] == null ? undefined : json['participant_ids'],
        'sourceType': json['source_type'] == null ? undefined : json['source_type'],
    };
}

export function CommondtoMemoryScopeToJSON(json: any): CommondtoMemoryScope {
    return CommondtoMemoryScopeToJSONTyped(json, false);
}

export function CommondtoMemoryScopeToJSONTyped(value?: CommondtoMemoryScope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actor_id': value['actorId'],
        'actor_name': value['actorName'],
        'actor_type': value['actorType'],
        'conversation_id': value['conversationId'],
        'participant_ids': value['participantIds'],
        'source_type': value['sourceType'],
    };
}

