/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemoryResponse } from './MemoryResponse';
import {
    MemoryResponseFromJSON,
    MemoryResponseFromJSONTyped,
    MemoryResponseToJSON,
    MemoryResponseToJSONTyped,
} from './MemoryResponse';
import type { Trace } from './Trace';
import {
    TraceFromJSON,
    TraceFromJSONTyped,
    TraceToJSON,
    TraceToJSONTyped,
} from './Trace';

/**
 * 
 * @export
 * @interface CreateMemoryResponse
 */
export interface CreateMemoryResponse {
    /**
     * 
     * @type {Trace}
     * @memberof CreateMemoryResponse
     */
    explainTrace?: Trace;
    /**
     * ExplicitSkip is true when the LLM intentionally extracted no facts; nothing was stored.
     * @type {boolean}
     * @memberof CreateMemoryResponse
     */
    explicitSkip?: boolean;
    /**
     * FactsExtracted is the number of discrete facts the LLM extracted from the input.
     * 0 when extraction is disabled (NoExtract/quick_search), when extraction fails,
     * when the LLM finds no facts (ExplicitSkip), or when passthrough applies.
     * @type {number}
     * @memberof CreateMemoryResponse
     */
    factsExtracted?: number;
    /**
     * Memories contains all memories created from the extracted facts.
     * When extraction is disabled or fails, this contains a single memory with the original content.
     * When ExplicitSkip is true (phatic / non-extractable content), this is empty.
     * @type {Array<MemoryResponse>}
     * @memberof CreateMemoryResponse
     */
    memories?: Array<MemoryResponse>;
    /**
     * SkippedCount is the number of facts skipped due to deduplication (exact duplicates).
     * @type {number}
     * @memberof CreateMemoryResponse
     */
    skippedCount?: number;
    /**
     * UpdatedCount is the number of facts that resulted in updates to existing memories.
     * @type {number}
     * @memberof CreateMemoryResponse
     */
    updatedCount?: number;
}

/**
 * Check if a given object implements the CreateMemoryResponse interface.
 */
export function instanceOfCreateMemoryResponse(value: object): value is CreateMemoryResponse {
    return true;
}

export function CreateMemoryResponseFromJSON(json: any): CreateMemoryResponse {
    return CreateMemoryResponseFromJSONTyped(json, false);
}

export function CreateMemoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMemoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'explainTrace': json['explain_trace'] == null ? undefined : TraceFromJSON(json['explain_trace']),
        'explicitSkip': json['explicit_skip'] == null ? undefined : json['explicit_skip'],
        'factsExtracted': json['facts_extracted'] == null ? undefined : json['facts_extracted'],
        'memories': json['memories'] == null ? undefined : ((json['memories'] as Array<any>).map(MemoryResponseFromJSON)),
        'skippedCount': json['skipped_count'] == null ? undefined : json['skipped_count'],
        'updatedCount': json['updated_count'] == null ? undefined : json['updated_count'],
    };
}

export function CreateMemoryResponseToJSON(json: any): CreateMemoryResponse {
    return CreateMemoryResponseToJSONTyped(json, false);
}

export function CreateMemoryResponseToJSONTyped(value?: CreateMemoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'explain_trace': TraceToJSON(value['explainTrace']),
        'explicit_skip': value['explicitSkip'],
        'facts_extracted': value['factsExtracted'],
        'memories': value['memories'] == null ? undefined : ((value['memories'] as Array<any>).map(MemoryResponseToJSON)),
        'skipped_count': value['skippedCount'],
        'updated_count': value['updatedCount'],
    };
}

