/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExplainStepTrace } from './ExplainStepTrace';
import {
    ExplainStepTraceFromJSON,
    ExplainStepTraceFromJSONTyped,
    ExplainStepTraceToJSON,
    ExplainStepTraceToJSONTyped,
} from './ExplainStepTrace';

/**
 * 
 * @export
 * @interface ExplainStageTrace
 */
export interface ExplainStageTrace {
    /**
     * DurationMs is the wall-clock duration of the stage.Execute() call.
     * @type {number}
     * @memberof ExplainStageTrace
     */
    durationMs?: number;
    /**
     * Error is the error string if the stage failed, empty on success.
     * @type {string}
     * @memberof ExplainStageTrace
     */
    error?: string;
    /**
     * InputJSON is the JSON-serialized stage input.
     * @type {string}
     * @memberof ExplainStageTrace
     */
    input?: string;
    /**
     * OutputJSON is the JSON-serialized stage output.
     * @type {string}
     * @memberof ExplainStageTrace
     */
    output?: string;
    /**
     * ResultCount is the number of results the stage produced.
     * For seed: len(SeedResults). For graph: len(GraphResult.Memories). For rerank: len(ScoredMemories).
     * @type {number}
     * @memberof ExplainStageTrace
     */
    resultCount?: number;
    /**
     * StageName identifies the stage ("seed", "graph", "rerank").
     * @type {string}
     * @memberof ExplainStageTrace
     */
    stageName?: string;
    /**
     * Steps contains the trace for each step executed within this stage.
     * @type {Array<ExplainStepTrace>}
     * @memberof ExplainStageTrace
     */
    steps?: Array<ExplainStepTrace>;
}

/**
 * Check if a given object implements the ExplainStageTrace interface.
 */
export function instanceOfExplainStageTrace(value: object): value is ExplainStageTrace {
    return true;
}

export function ExplainStageTraceFromJSON(json: any): ExplainStageTrace {
    return ExplainStageTraceFromJSONTyped(json, false);
}

export function ExplainStageTraceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExplainStageTrace {
    if (json == null) {
        return json;
    }
    return {
        
        'durationMs': json['duration_ms'] == null ? undefined : json['duration_ms'],
        'error': json['error'] == null ? undefined : json['error'],
        'input': json['input'] == null ? undefined : json['input'],
        'output': json['output'] == null ? undefined : json['output'],
        'resultCount': json['result_count'] == null ? undefined : json['result_count'],
        'stageName': json['stage_name'] == null ? undefined : json['stage_name'],
        'steps': json['steps'] == null ? undefined : ((json['steps'] as Array<any>).map(ExplainStepTraceFromJSON)),
    };
}

export function ExplainStageTraceToJSON(json: any): ExplainStageTrace {
    return ExplainStageTraceToJSONTyped(json, false);
}

export function ExplainStageTraceToJSONTyped(value?: ExplainStageTrace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration_ms': value['durationMs'],
        'error': value['error'],
        'input': value['input'],
        'output': value['output'],
        'result_count': value['resultCount'],
        'stage_name': value['stageName'],
        'steps': value['steps'] == null ? undefined : ((value['steps'] as Array<any>).map(ExplainStepTraceToJSON)),
    };
}

