/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FactExtractionOverrides
 */
export interface FactExtractionOverrides {
    /**
     * 
     * @type {number}
     * @memberof FactExtractionOverrides
     */
    minImportance?: number;
    /**
     * Model has no effect today: the model comes from the system AI connection. Reserved for model
     * selection by criteria, allowed only for apps that use their own AI (custom AI / BYOK).
     * @type {string}
     * @memberof FactExtractionOverrides
     */
    model?: string;
    /**
     * 
     * @type {FactExtractionOverridesStrategyEnum}
     * @memberof FactExtractionOverrides
     */
    strategy?: FactExtractionOverridesStrategyEnum;
}


/**
 * @export
 */
export const FactExtractionOverridesStrategyEnum = {
    LlmFactExtraction: 'llm_fact_extraction'
} as const;
export type FactExtractionOverridesStrategyEnum = typeof FactExtractionOverridesStrategyEnum[keyof typeof FactExtractionOverridesStrategyEnum];


/**
 * Check if a given object implements the FactExtractionOverrides interface.
 */
export function instanceOfFactExtractionOverrides(value: object): value is FactExtractionOverrides {
    return true;
}

export function FactExtractionOverridesFromJSON(json: any): FactExtractionOverrides {
    return FactExtractionOverridesFromJSONTyped(json, false);
}

export function FactExtractionOverridesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FactExtractionOverrides {
    if (json == null) {
        return json;
    }
    return {
        
        'minImportance': json['min_importance'] == null ? undefined : json['min_importance'],
        'model': json['model'] == null ? undefined : json['model'],
        'strategy': json['strategy'] == null ? undefined : json['strategy'],
    };
}

export function FactExtractionOverridesToJSON(json: any): FactExtractionOverrides {
    return FactExtractionOverridesToJSONTyped(json, false);
}

export function FactExtractionOverridesToJSONTyped(value?: FactExtractionOverrides | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_importance': value['minImportance'],
        'model': value['model'],
        'strategy': value['strategy'],
    };
}

