/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommondtoRelativeStandingConfig } from './CommondtoRelativeStandingConfig';
import {
    CommondtoRelativeStandingConfigFromJSON,
    CommondtoRelativeStandingConfigFromJSONTyped,
    CommondtoRelativeStandingConfigToJSON,
    CommondtoRelativeStandingConfigToJSONTyped,
} from './CommondtoRelativeStandingConfig';
import type { CommondtoMemoryScope } from './CommondtoMemoryScope';
import {
    CommondtoMemoryScopeFromJSON,
    CommondtoMemoryScopeFromJSONTyped,
    CommondtoMemoryScopeToJSON,
    CommondtoMemoryScopeToJSONTyped,
} from './CommondtoMemoryScope';
import type { ExplainTrace } from './ExplainTrace';
import {
    ExplainTraceFromJSON,
    ExplainTraceFromJSONTyped,
    ExplainTraceToJSON,
    ExplainTraceToJSONTyped,
} from './ExplainTrace';

/**
 * 
 * @export
 * @interface MemoryCreateMemoryResponse
 */
export interface MemoryCreateMemoryResponse {
    /**
     * 
     * @type {string}
     * @memberof MemoryCreateMemoryResponse
     */
    activeFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof MemoryCreateMemoryResponse
     */
    activeTo?: string;
    /**
     * 
     * @type {string}
     * @memberof MemoryCreateMemoryResponse
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof MemoryCreateMemoryResponse
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof MemoryCreateMemoryResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {ExplainTrace}
     * @memberof MemoryCreateMemoryResponse
     */
    explainTrace?: ExplainTrace;
    /**
     * 
     * @type {string}
     * @memberof MemoryCreateMemoryResponse
     */
    id?: string;
    /**
     * 
     * @type {object}
     * @memberof MemoryCreateMemoryResponse
     */
    metadata?: object;
    /**
     * 
     * @type {CommondtoRelativeStandingConfig}
     * @memberof MemoryCreateMemoryResponse
     */
    relativeStanding?: CommondtoRelativeStandingConfig;
    /**
     * Scope contains the memory's actor, conversation, and source context.
     * @type {CommondtoMemoryScope}
     * @memberof MemoryCreateMemoryResponse
     */
    scope?: CommondtoMemoryScope;
    /**
     * 
     * @type {string}
     * @memberof MemoryCreateMemoryResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the MemoryCreateMemoryResponse interface.
 */
export function instanceOfMemoryCreateMemoryResponse(value: object): value is MemoryCreateMemoryResponse {
    return true;
}

export function MemoryCreateMemoryResponseFromJSON(json: any): MemoryCreateMemoryResponse {
    return MemoryCreateMemoryResponseFromJSONTyped(json, false);
}

export function MemoryCreateMemoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryCreateMemoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'activeFrom': json['active_from'] == null ? undefined : json['active_from'],
        'activeTo': json['active_to'] == null ? undefined : json['active_to'],
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'explainTrace': json['explain_trace'] == null ? undefined : ExplainTraceFromJSON(json['explain_trace']),
        'id': json['id'] == null ? undefined : json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'relativeStanding': json['relative_standing'] == null ? undefined : CommondtoRelativeStandingConfigFromJSON(json['relative_standing']),
        'scope': json['scope'] == null ? undefined : CommondtoMemoryScopeFromJSON(json['scope']),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function MemoryCreateMemoryResponseToJSON(json: any): MemoryCreateMemoryResponse {
    return MemoryCreateMemoryResponseToJSONTyped(json, false);
}

export function MemoryCreateMemoryResponseToJSONTyped(value?: MemoryCreateMemoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_from': value['activeFrom'],
        'active_to': value['activeTo'],
        'app_id': value['appId'],
        'content': value['content'],
        'created_at': value['createdAt'],
        'explain_trace': ExplainTraceToJSON(value['explainTrace']),
        'id': value['id'],
        'metadata': value['metadata'],
        'relative_standing': CommondtoRelativeStandingConfigToJSON(value['relativeStanding']),
        'scope': CommondtoMemoryScopeToJSON(value['scope']),
        'updated_at': value['updatedAt'],
    };
}

