/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemorySearchMemoryResponse } from './MemorySearchMemoryResponse';
import {
    MemorySearchMemoryResponseFromJSON,
    MemorySearchMemoryResponseFromJSONTyped,
    MemorySearchMemoryResponseToJSON,
    MemorySearchMemoryResponseToJSONTyped,
} from './MemorySearchMemoryResponse';

/**
 * 
 * @export
 * @interface MemorySearchMemoriesResponse
 */
export interface MemorySearchMemoriesResponse {
    /**
     * 
     * @type {Array<MemorySearchMemoryResponse>}
     * @memberof MemorySearchMemoriesResponse
     */
    memories?: Array<MemorySearchMemoryResponse>;
}

/**
 * Check if a given object implements the MemorySearchMemoriesResponse interface.
 */
export function instanceOfMemorySearchMemoriesResponse(value: object): value is MemorySearchMemoriesResponse {
    return true;
}

export function MemorySearchMemoriesResponseFromJSON(json: any): MemorySearchMemoriesResponse {
    return MemorySearchMemoriesResponseFromJSONTyped(json, false);
}

export function MemorySearchMemoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemorySearchMemoriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'memories': json['memories'] == null ? undefined : ((json['memories'] as Array<any>).map(MemorySearchMemoryResponseFromJSON)),
    };
}

export function MemorySearchMemoriesResponseToJSON(json: any): MemorySearchMemoriesResponse {
    return MemorySearchMemoriesResponseToJSONTyped(json, false);
}

export function MemorySearchMemoriesResponseToJSONTyped(value?: MemorySearchMemoriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memories': value['memories'] == null ? undefined : ((value['memories'] as Array<any>).map(MemorySearchMemoryResponseToJSON)),
    };
}

