/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemoryMemoryResponse } from './MemoryMemoryResponse';
import {
    MemoryMemoryResponseFromJSON,
    MemoryMemoryResponseFromJSONTyped,
    MemoryMemoryResponseToJSON,
    MemoryMemoryResponseToJSONTyped,
} from './MemoryMemoryResponse';

/**
 * 
 * @export
 * @interface MemorySearchMemoryResponse
 */
export interface MemorySearchMemoryResponse {
    /**
     * 
     * @type {MemoryMemoryResponse}
     * @memberof MemorySearchMemoryResponse
     */
    memory?: MemoryMemoryResponse;
    /**
     * 
     * @type {number}
     * @memberof MemorySearchMemoryResponse
     */
    score?: number;
}

/**
 * Check if a given object implements the MemorySearchMemoryResponse interface.
 */
export function instanceOfMemorySearchMemoryResponse(value: object): value is MemorySearchMemoryResponse {
    return true;
}

export function MemorySearchMemoryResponseFromJSON(json: any): MemorySearchMemoryResponse {
    return MemorySearchMemoryResponseFromJSONTyped(json, false);
}

export function MemorySearchMemoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemorySearchMemoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'memory': json['memory'] == null ? undefined : MemoryMemoryResponseFromJSON(json['memory']),
        'score': json['score'] == null ? undefined : json['score'],
    };
}

export function MemorySearchMemoryResponseToJSON(json: any): MemorySearchMemoryResponse {
    return MemorySearchMemoryResponseToJSONTyped(json, false);
}

export function MemorySearchMemoryResponseToJSONTyped(value?: MemorySearchMemoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memory': MemoryMemoryResponseToJSON(value['memory']),
        'score': value['score'],
    };
}

