/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemorySearchMemoryResult
 */
export interface MemorySearchMemoryResult {
    /**
     * ActiveFrom is when this fact became true (event timestamp, not DB insertion time).
     * @type {string}
     * @memberof MemorySearchMemoryResult
     */
    activeFrom?: string;
    /**
     * ActiveTo is when this fact stopped being true (nil = still valid).
     * Unique to smritea — enables temporal reasoning (e.g., "worked at X until Y").
     * @type {string}
     * @memberof MemorySearchMemoryResult
     */
    activeTo?: string;
    /**
     * ActorID identifies whose memory this is.
     * @type {string}
     * @memberof MemorySearchMemoryResult
     */
    actorId?: string;
    /**
     * ActorName is the human-readable name of the actor.
     * @type {string}
     * @memberof MemorySearchMemoryResult
     */
    actorName?: string;
    /**
     * ActorType is the type of actor (user|agent|system).
     * @type {MemorySearchMemoryResultActorTypeEnum}
     * @memberof MemorySearchMemoryResult
     */
    actorType?: MemorySearchMemoryResultActorTypeEnum;
    /**
     * Content is the memory text — the core payload for search consumers.
     * @type {string}
     * @memberof MemorySearchMemoryResult
     */
    content?: string;
    /**
     * ConversationID is the conversation this memory belongs to (optional).
     * @type {string}
     * @memberof MemorySearchMemoryResult
     */
    conversationId?: string;
    /**
     * ID is the memory identifier, needed for follow-up operations (update/delete).
     * @type {string}
     * @memberof MemorySearchMemoryResult
     */
    id?: string;
    /**
     * Metadata contains caller-defined key-value pairs (omitted when empty).
     * @type {object}
     * @memberof MemorySearchMemoryResult
     */
    metadata?: object;
}


/**
 * @export
 */
export const MemorySearchMemoryResultActorTypeEnum = {
    User: 'user',
    Agent: 'agent',
    System: 'system'
} as const;
export type MemorySearchMemoryResultActorTypeEnum = typeof MemorySearchMemoryResultActorTypeEnum[keyof typeof MemorySearchMemoryResultActorTypeEnum];


/**
 * Check if a given object implements the MemorySearchMemoryResult interface.
 */
export function instanceOfMemorySearchMemoryResult(value: object): value is MemorySearchMemoryResult {
    return true;
}

export function MemorySearchMemoryResultFromJSON(json: any): MemorySearchMemoryResult {
    return MemorySearchMemoryResultFromJSONTyped(json, false);
}

export function MemorySearchMemoryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemorySearchMemoryResult {
    if (json == null) {
        return json;
    }
    return {
        
        'activeFrom': json['active_from'] == null ? undefined : json['active_from'],
        'activeTo': json['active_to'] == null ? undefined : json['active_to'],
        'actorId': json['actor_id'] == null ? undefined : json['actor_id'],
        'actorName': json['actor_name'] == null ? undefined : json['actor_name'],
        'actorType': json['actor_type'] == null ? undefined : json['actor_type'],
        'content': json['content'] == null ? undefined : json['content'],
        'conversationId': json['conversation_id'] == null ? undefined : json['conversation_id'],
        'id': json['id'] == null ? undefined : json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function MemorySearchMemoryResultToJSON(json: any): MemorySearchMemoryResult {
    return MemorySearchMemoryResultToJSONTyped(json, false);
}

export function MemorySearchMemoryResultToJSONTyped(value?: MemorySearchMemoryResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_from': value['activeFrom'],
        'active_to': value['activeTo'],
        'actor_id': value['actorId'],
        'actor_name': value['actorName'],
        'actor_type': value['actorType'],
        'content': value['content'],
        'conversation_id': value['conversationId'],
        'id': value['id'],
        'metadata': value['metadata'],
    };
}

