/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SearchStrategiesSearchMethod = {
    SearchMethodQuickSearch: 'quick_search',
    SearchMethodDeepSearch: 'deep_search',
    SearchMethodContextAwareSearch: 'context_aware_search',
    SearchMethodGraphProximity: 'graph_proximity',
    SearchMethodDiversified: 'diversified',
    SearchMethodSemanticRerank: 'semantic_rerank'
} as const;
export type SearchStrategiesSearchMethod = typeof SearchStrategiesSearchMethod[keyof typeof SearchStrategiesSearchMethod];


export function instanceOfSearchStrategiesSearchMethod(value: any): boolean {
    for (const key in SearchStrategiesSearchMethod) {
        if (Object.prototype.hasOwnProperty.call(SearchStrategiesSearchMethod, key)) {
            if (SearchStrategiesSearchMethod[key as keyof typeof SearchStrategiesSearchMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SearchStrategiesSearchMethodFromJSON(json: any): SearchStrategiesSearchMethod {
    return SearchStrategiesSearchMethodFromJSONTyped(json, false);
}

export function SearchStrategiesSearchMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchStrategiesSearchMethod {
    return json as SearchStrategiesSearchMethod;
}

export function SearchStrategiesSearchMethodToJSON(value?: SearchStrategiesSearchMethod | null): any {
    return value as any;
}

export function SearchStrategiesSearchMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): SearchStrategiesSearchMethod {
    return value as SearchStrategiesSearchMethod;
}

