/* tslint:disable */
/* eslint-disable */
/**
 * smritea SDK API
 * Public SDK API for smritea AI memory system — programmatic memory operations via API key
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StepTrace
 */
export interface StepTrace {
    /**
     * DurationMs is the wall-clock duration of the step.Execute() call.
     * @type {number}
     * @memberof StepTrace
     */
    durationMs?: number;
    /**
     * Error is the error string if the step failed, empty on success.
     * @type {string}
     * @memberof StepTrace
     */
    error?: string;
    /**
     * InputJSON is the JSON-serialized step input.
     * @type {string}
     * @memberof StepTrace
     */
    input?: string;
    /**
     * OutputJSON is the JSON-serialized step output.
     * @type {string}
     * @memberof StepTrace
     */
    output?: string;
    /**
     * ResultCount is the number of results the step produced.
     * @type {number}
     * @memberof StepTrace
     */
    resultCount?: number;
    /**
     * StepName is the step's Name() return value.
     * @type {string}
     * @memberof StepTrace
     */
    stepName?: string;
}

/**
 * Check if a given object implements the StepTrace interface.
 */
export function instanceOfStepTrace(value: object): value is StepTrace {
    return true;
}

export function StepTraceFromJSON(json: any): StepTrace {
    return StepTraceFromJSONTyped(json, false);
}

export function StepTraceFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepTrace {
    if (json == null) {
        return json;
    }
    return {
        
        'durationMs': json['duration_ms'] == null ? undefined : json['duration_ms'],
        'error': json['error'] == null ? undefined : json['error'],
        'input': json['input'] == null ? undefined : json['input'],
        'output': json['output'] == null ? undefined : json['output'],
        'resultCount': json['result_count'] == null ? undefined : json['result_count'],
        'stepName': json['step_name'] == null ? undefined : json['step_name'],
    };
}

export function StepTraceToJSON(json: any): StepTrace {
    return StepTraceToJSONTyped(json, false);
}

export function StepTraceToJSONTyped(value?: StepTrace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration_ms': value['durationMs'],
        'error': value['error'],
        'input': value['input'],
        'output': value['output'],
        'result_count': value['resultCount'],
        'step_name': value['stepName'],
    };
}

